### ISSUE TITLE
Include git sha in repository snapshot names

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1003]
**Is your feature request related to a problem? Please describe.**
Currently repository snapshots are prefixed only by date, which makes difficult to track back to the actual commit/tag. `luet create-repo` takes a `--snapshot-id` argument, so we can use that while pushing with the CI. While promoting snapshots, we can stop also indexing all packages (which would alleviate a bit of work from the CI), so this card is also about adapting our CI.

**Describe the solution you'd like**

- [x] snapshots to include the git sha/tag
- [x] releases to include also a file with the repository references of the release
- [x] stop indexing all packages. as we can rely on snapshots we can just publish the current repository state. https://github.com/rancher-sandbox/cOS-toolkit/blob/c981c45e3fff1f0337d549ad5d8acdf269f69f9b/.github/build.yaml.gomplate#L567

**Describe alternatives you've considered**

**Additional context**
Depends on #985

**Comment by Itxaka** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/pull/1312 for the snapshot-id of both commits and tags

**Comment by Itxaka** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/pull/1314 for  `releases to include also a file with the repository references of the release`

**Comment by Itxaka** [comment]
umm @mudler Im not sure hwo to approach `stop indexing all packages. as we can rely on snapshots we can just publish the current repository state. [master/.github/build.yaml.gomplate#L557](https://github.com/rancher-sandbox/cOS-toolkit/blob/master/.github/build.yaml.gomplate#L557)`

Is that done on the build.go code? Like it should get a repositoryID reference in order to check the artifacts for that or....

Im a bit lost on that part, as I have no idea how we index everything. I guess the DOWNLOAD_ALL stuff will also had something to do with that?

**Comment by mudler** [comment]
> umm @mudler Im not sure hwo to approach `stop indexing all packages. as we can rely on snapshots we can just publish the current repository state. [master/.github/build.yaml.gomplate#L557](https://github.com/rancher-sandbox/cOS-toolkit/blob/master/.github/build.yaml.gomplate#L557)`
> 
> Is that done on the build.go code? Like it should get a repositoryID reference in order to check the artifacts for that or....
> 
> Im a bit lost on that part, as I have no idea how we index everything. I guess the DOWNLOAD_ALL stuff will also had something to do with that?

Sorry the late reply, I've lost this comment. 

Yes DOWNLOAD_ALL has the effect of downloading all the previous index meta, so it keeps getting included between publish calls.

To disable that behavior it is enough to drop that ENV var https://github.com/rancher-sandbox/cOS-toolkit/blob/c981c45e3fff1f0337d549ad5d8acdf269f69f9b/.github/build.yaml.gomplate#L567 
It is used like so: https://github.com/rancher-sandbox/cOS-toolkit/blob/5bf6a9184571a082a11bfcbd88eb0ee4bfd78cb7/.github/build.go#L175

**Comment by Itxaka** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/pull/1318 for the indexing
