### ISSUE TITLE
Parse standard cloud-init structure in yip as well

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#104]
Currently `yip` has it's own syntax to read yaml file. This card is about augmenting `yip` in order to read and support  from the original [cloud-config spec](http://cloudinit.readthedocs.org/en/latest/topics/format.html#cloud-config-data) for the most important features, e.g.:

- [x] writing files
- [x] ssh keys / users
- [x] writing directories
- [x] script commands
- [ ] dns setup

PR: https://github.com/mudler/yip/pull/3 . It consumes the cloud-init forks to parse similarly as coreOS. The details are attached in the link above

**Comment by kkaempf** [comment]
How does this match with #108 ("yip can be used already as a standalone module and **replaced by a fusionkit-cloudinit**") ?

**Comment by mudler** [comment]
This is about enlarging the yaml syntax that we can currently parse, because `yip` has its own, #108 is embedding the current featureset in its own cli, as `yip` itself can be just used as module from a single cli UX

**Comment by mudler** [comment]
#119 was merged with the above change included
