### ISSUE TITLE
Environment variable configuration

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1050]
- [x] Viper configuration for reading from config files (ping @mudler)
- [x] Reading from environment variable
- [x] Configuration from env file: `/etc/os-release`, `/etc/cos/config`

**Comment by Itxaka** [comment]
For "Configuration from env file: /etc/os-release, /etc/cos/config" I got https://github.com/rancher-sandbox/elemental-cli/pull/42

For " Reading from environment variable" there is already something in place, but its using the ELEMENTAL prefix. Do we want to keep that and modify our config files to support that or we drop it and use the vars directly without any prefix? I would vote for making them more explicit, as its clear what those env vars are for if they are prefixed like that, but it would break backwards compatibility so....

For "Viper configuration for reading from config files (ping @mudler)" there is already something in place that reads from a config dir (set by "config-dir", we only need to enable the global flag) and also tries to read from `config-dir`/config.d/ any extra files dropped in there, which allows for nice overriding of values, even if we ship some defaults in the config file. Not sure what else is needed in there @mudler ?

CC @davidcassany @mudler @dragonchaser

**Comment by Itxaka** [comment]
Viper config from config files already added to https://github.com/rancher-sandbox/elemental-cli/pull/42

**Comment by davidcassany** [comment]
> For " Reading from environment variable" there is already something in place, but its using the ELEMENTAL prefix. Do we want to keep that and modify our config files to support that or we drop it and use the vars directly without any prefix? I would vote for making them more explicit, as its clear what those env vars are for if they are prefixed like that, but it would break backwards compatibility so....

I vote to keep the prefix, I also like the idea of making supported environment variables explicit by some sort of prefix.

**Comment by mudler** [comment]
> For "Configuration from env file: /etc/os-release, /etc/cos/config" I got [rancher-sandbox/elemental-cli#42](https://github.com/rancher-sandbox/elemental-cli/pull/42)
> 
> For " Reading from environment variable" there is already something in place, but its using the ELEMENTAL prefix. Do we want to keep that and modify our config files to support that or we drop it and use the vars directly without any prefix? I would vote for making them more explicit, as its clear what those env vars are for if they are prefixed like that, but it would break backwards compatibility so....
> 
> For "Viper configuration for reading from config files (ping @mudler)" there is already something in place that reads from a config dir (set by "config-dir", we only need to enable the global flag) and also tries to read from `config-dir`/config.d/ any extra files dropped in there, which allows for nice overriding of values, even if we ship some defaults in the config file. Not sure what else is needed in there @mudler ?
> 
> CC @davidcassany @mudler @dragonchaser

I'd say with [rancher-sandbox/elemental-cli#42](https://github.com/rancher-sandbox/elemental-cli/pull/42) we are good here then, we can make a breaking change on the default config file so to force a prefix to them. It is also more clean so in external files (like, `os-release`) it's entirely separated, avoiding clashing with others. 

During upgrades this shouldn't be an issue in both kubernetes and manual upgrades. the Image running the upgrades is the one which is targeted , so the new image would have the correct configuration files, while triggering manual is the old image running them, which still reads the configuration file from the bash part. 

The only maybe tricky aspect would be grub branding changes as it involves chrooting, and that might break in manual upgrades.

**Comment by Itxaka** [comment]
nice, then marking this as completed!
