### ISSUE TITLE
Hide hook cos-setup messages from cos.sh output

### ISSUE THREAD

**Issue by bk201** [rancher-sandbox/cOS-toolkit#1053]
**Is your feature request related to a problem? Please describe.**
There are hook yip logs during installation, it would be nice to have an option to hide them.

e.g.,

![148959889-62a7f0a8-696f-4b23-8d24-611a5f4da3ef](https://user-images.githubusercontent.com/1691518/149060513-6e7c2f12-868a-4051-8280-911e8c272695.png)

**Describe the solution you'd like**

An environment variable or option to hide hook messages.

**Describe alternatives you've considered**

Leave it alone. That's no harm at all.

**Additional context**

https://github.com/harvester/harvester-installer/pull/210#pullrequestreview-849244708

**Comment by Itxaka** [comment]
is this only for hooks or would an option (--quiet) that silences everything also be good?

Maybe we should ahve 2 options, one called `--script` so this can be run from scripts and all output silenced, so we can use the exit status only and one called `--silence-hooks` to avoid printing only the hooks?

**Comment by Itxaka** [comment]
new option `--silence-hooks` added which should set the yip log level to errors only
