### ISSUE TITLE
Review installer `--iso` behavior

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#1054]
At a glance it looks like the current behavior of `--iso` flag in `cos-installer` script is not obvious and rare. This was seen while porting all the installer flags to the elemental-cli. This card is devoted to clarify the desired behavior of this flag and implement it in elemental-cli. This should help to clarify some of the non obvious logic in `CopyRecovery` method: 
https://github.com/rancher-sandbox/elemental-cli/blob/de49930db138d8306be8d3cb869f1abdc1331833/pkg/elemental/elemental.go#L418-L430

IMHO the `--iso` flag should mean:

1. Download ISO
2. Mount ISO
3. Use ISO's system image as Active image
4. Use recovery squashfs image if any or reuse Active as recovery instead.
5. This is all independent of booting from an ISO or not

**Comment by davidcassany** [comment]
I came to the conclusion that some of this strange logic is probably there because at some point we considered calling `cos-installer` from the recovery partition against the current device. I believe this is a wrong approach and something we should not consider, for this kind of scenarios we should be using `cos-deploy` (or similar) procedures.

**Comment by Itxaka** [comment]
well, some of the cos-deploy functions were kind of folder into the cos.installer so maybe it comes from that part? On packer build we no longer use cos-deploy but cos-installer directly, maybe the reasoning was to fold everything into just one script?

**Comment by Itxaka** [comment]
ah in fact, cos-deploy now just calls cos-installer internally, so probably is coming from that side...

**Comment by mudler** [comment]
This potentially impacts both os2 and harvester, for os2 the description above is how it should have been behaving, so this probably is a regression from an earlier refactor as we don't test automatically installation from remote ISOs.

cc @bk201 how the harvester team is using this feature? or is not using it at all in place of a custom logic?

**Comment by bk201** [comment]
@mudler Thanks for pinging. Harvester doesn't rely on cos script to handle ISOs (it [omits the `_COS_INSTALL_ISO_URL` environment variable](https://github.com/harvester/harvester-installer/blob/a3e4afaa6b50a67159df78d70d6f92fe99bc3a3a/package/harvester-os/files/usr/sbin/harv-install#L341)). Instead, we do the ISO stuff after the OS is installed (for example, we can fetch the ISO to target OS's `/usr/local/` instread of tmpfs in memory)

But the description in this issue might potentially break Harvester's use because it tries to use the system image in the ISO, rather than using what is mounted under `/run/rootfsbase`.

**Comment by bk201** [comment]
@davidcassany Sure, they are located at https://github.com/harvester/harvester-installer/blob/954cc1170a36d82658f38a964da50efeb0c77690/package/harvester-os/files/usr/sbin/harv-install#L347-L352

cos script is called beforehand: https://github.com/harvester/harvester-installer/blob/954cc1170a36d82658f38a964da50efeb0c77690/package/harvester-os/files/usr/sbin/harv-install#L341

**Comment by davidcassany** [comment]
@mudler Beyond the description above of this issue I realized about another behavior that is weird to me. In our current setup the story behind squashfs recovery vs nonsquashfs recovery depends on the installation media having or not a separate recovery devoted image. To me these are completely ortogonal things, having a squashfs recovery or not has no relation to the fact if we are using a different image for active and recovery.

To me, a more reasonable behavior would be:

* Reuse active image if the installation media (or config) does not provide a recovery specific image
* Recovery image is squashfs by default, but we have a `--no-squashfs` flag to change it

This way we could eventually reuse the same ISO (the one including a system and recovery separated images) to install both scenarios (squash and nonsquashfs).

I think this could fall on the scope of this issue as this related on how to handle the fetched ISO and its active and recovery images. I also noted that current `--iso` implementation does not support ISOs without a recovery image 😓

**Comment by davidcassany** [comment]
> @davidcassany Sure, they are located at https://github.com/harvester/harvester-installer/blob/954cc1170a36d82658f38a964da50efeb0c77690/package/harvester-os/files/usr/sbin/harv-install#L347-L352
> 
> cos script is called beforehand: https://github.com/harvester/harvester-installer/blob/954cc1170a36d82658f38a964da50efeb0c77690/package/harvester-os/files/usr/sbin/harv-install#L341

I see, thanks for the pointers. As far as I can see there is no potential interaction with the `elemental install` and its `--iso` flag/feature between the Harvester installer script. If I am not wrong the ISO logic in Harvester is not reusing anything from cOS, beyond the ISO artifact itself (which is not affected by this issue). All Harvester installer logic devoted to ISOs is custom logic disconnected from `cos.sh`. My expectation is that on Harvester you could use `elemental install` (and adjust env variables names) instead of `cos install` and the fetch ISO feature should remain completely equivalent.

**Comment by mudler** [comment]
> @mudler Beyond the description above of this issue I realized about another behavior that is weird to me. In our current setup the story behind squashfs recovery vs nonsquashfs recovery depends on the installation media having or not a separate recovery devoted image. To me these are completely ortogonal things, having a squashfs recovery or not has no relation to the fact if we are using a different image for active and recovery.

It is not entirely like that, that is just part of the story which holds only for installation indeed. If there is a squashfs recovery file, then cOS reads it, but it's not meant only the installation to have a logic on that part.

During the cos recovery upgrade, the former bash script used to check if a squashfs file was present or not in the system and accordingly updates depending on that (if there is a squashfs, the recovery upgrade was going to rebuild a squash fs file, and so on), and similarly booting falls back to recovery if no image is present. That leaves an open mechanism to replace recovery with squashfs or with images also after install (because cOS detects it, and doesn't enforce any)

> 
> To me, a more reasonable behavior would be:
> 
>     * Reuse active image if the installation media (or config) does not provide a recovery specific image
> 
>     * Recovery image is squashfs by default, but we have a `--no-squashfs` flag to change it
> 

That's perfectly inline with the detection part, if we don't write a squashfs file, then we don't read from it and read the image file

**Comment by mudler** [comment]
> @davidcassany Sure, they are located at https://github.com/harvester/harvester-installer/blob/954cc1170a36d82658f38a964da50efeb0c77690/package/harvester-os/files/usr/sbin/harv-install#L347-L352
> 
> cos script is called beforehand: https://github.com/harvester/harvester-installer/blob/954cc1170a36d82658f38a964da50efeb0c77690/package/harvester-os/files/usr/sbin/harv-install#L341

thanks a lot for the inputs @bk201 ! seems we should be fine here and not have any impact as we are not mutating layout, but just the installation steps taken if an iso url is specified to the elemental installer.

From what I can see seems you are completely detached from that as the ISO is used for preloading the docker images, or I'm missing something other bits around it?

**Comment by davidcassany** [comment]
My point is that with this logic it is only possible to have a non squashfs recovery if this is the same content as active. From a matrix of four cases (active image vs recovery img have different content, and recovery is an squashfs image or not)  we are only supporting two with a non explicit setup.

I find this logic of checking for squashfs to test if active img and recovery img are the same weird, to me it feels this should be a config flag, probably instead of having a `--no-squasfs` there could be a flag to state recovery and active are the same.

Anyway this is a small detail for now, probably better leave it for later.
