### ISSUE TITLE
Installing not from an ISO using the upgrade channel.

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#1059]
`cos-installer` if executed not from an installation ISO it tries to determine an upgrade channel from the current system and use that to install the system.

IMHO this behavior is obscure and error prone, due to this kind of magic we have #1054. I believe it would be way simpler to allow to set the upgrade channel from the command line so we can use upgrade channel regardless of being executed from an ISO or not. That covers using the upgrade channel in ISO and non ISO scenarios without business logic differences.

**Comment by mudler** [comment]
this ties also with https://github.com/rancher-sandbox/cOS-toolkit/pull/1040

**Comment by davidcassany** [comment]
This is already coded as part of rancher-sandbox/elemental#132, closing
