### ISSUE TITLE
CI: make builds faster and more consistent

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#106]
At the moment the CI it's having several shortcomings. In case of a job failure, the whole pipeline have to run and regenerate all the assets (ISO, qemu images, and vbox) which makes the development rather slow. One idea to improve that is to reuse cached assets

**Comment by Itxaka** [comment]
After several PRs we have brought this down to a bit over 1 hour (https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/795034500 for example)

I dont think we will be able to further reduce this down more as we are now constrained by the speed of the free github workers.

The worst part is still the `test-upgrades-images-unsigned` tests which takes about 30 minutes. We could probably split those even further to try to run them in parallel which *should* retuls in a 15 minutes job, but still... 10 minutes for build + 5 minutes for iso + 20 minutes for qemu + 15 minutes for tests + 5 minutes for publish gets us 55 minutes which is not far from our current time.

I still got https://github.com/rancher-sandbox/cOS-toolkit/pull/120 in there which would split the jobs into 3 different pipelines, one per flavor, but Im not sure if we want to add that complexity for a 10 minute gain and unknown consecuences (Queue size? How many steps are we able to run in parallel? Will it affect our *main* job (opensuse) having to run the other?)

From my POV this is as far as we can get without moving to our own runners and having the workflows simple enough.

**Comment by kkaempf** [comment]
I gave self-hosted runners a try earlier this week. The current `build.yaml` is (a) heavily Ubuntu-specific and (b) relies on 'fresh' (resp. clean) workers a lot. Also we would need multiple self-hosted runners for parallelism.

We need to augment tests to clean up afterwards first. Which is not a bad thing to do imho :wink:

**Comment by mudler** [comment]
I think we are good to close this. We have self-hosted runners and GHA runners as well which are working fine. There are some shortcomings on EFI tests but that's out of our control. 

Now that Github Action also supports re-running individual jobs, I think that covers what was mostly left here in this card, hence closing it.
