### ISSUE TITLE
CI fails with 'unknown blob'

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1067]
First occurrence: https://github.com/rancher-sandbox/cOS-toolkit/runs/4823380217?check_suite_focus=true
Last green good build of system/cos: https://github.com/rancher-sandbox/cOS-toolkit/runs/4794928114?check_suite_focus=true
Seems to happen while the CI pushes docker images to quay, so it doesn't affects PR directly:
**Logs**
```
           ae6a05b80b58: Layer already exists
          d334c8612dc4: Pushed
          063be5e6f3e2: Pushed
          unknown blob
```

**Comment by mudler** [comment]
Raising prio as it is blocking master now

**Comment by mudler** [comment]
Note: in https://github.com/rancher-sandbox/cOS-toolkit/runs/4823380292?check_suite_focus=true it failed on system/cos-img, while currently seems to affect only system/cos. Could it be a registry issue?

**Comment by mudler** [comment]
Here failed pushing golang: https://github.com/rancher-sandbox/cOS-toolkit/runs/4838878246?check_suite_focus=true

**Comment by mudler** [comment]
Here rancherd: https://github.com/rancher-sandbox/cOS-toolkit/runs/4838878214?check_suite_focus=true

**Comment by Itxaka** [comment]
well, this points to a registry issue then, if its not centered around 1 single artifact push then?

**Comment by mudler** [comment]
Here failed with nerdctl: https://github.com/rancher-sandbox/cOS-toolkit/runs/4838880211?check_suite_focus=true

**Comment by mudler** [comment]
Seems getting better now. at least system/cos is pushed here: https://github.com/rancher-sandbox/cOS-toolkit/runs/4842740221?check_suite_focus=true

**Comment by Itxaka** [comment]
Looks like its kind of fixed? https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/1707481998

**Comment by mudler** [comment]
Looks like it, closing
