### ISSUE TITLE
Add checksum verification for assets downloaded externally

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#113]
We need to add checksum verification for the assets downloaded during packagebuild, coming from outside.

Those includes:
- livecd/systemd-boot
- livecd/syslinux
- build/golang

~~Our automated [CI bump-bot](https://github.com/Luet-lab/extensions/tree/master/extensions/autobump-github) should update the checksum accordingly when opening new PR.~~ This has been done separately, see https://github.com/rancher-sandbox/cOS-toolkit/pull/229/files

The only two other components are `yip` and `luet` but with #108 won't be needed anymore.

## Requirements

 - [x] External assets have a checksum 
   - [x] https://github.com/rancher-sandbox/cOS-toolkit/pull/229 
   - [x] https://github.com/rancher-sandbox/cOS-toolkit/pull/230
 - [x] That checksum is checked during package build

**Comment by mudler** [comment]
This is part of #95 which is required for MVP

**Comment by mudler** [comment]
I'll split the CI autobump in a separate story

**Comment by Itxaka** [comment]
All PRs merged!
