### ISSUE TITLE
Generated ISOs are not 'valid' hybrid

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1148]
**cos-toolkit version:**

**CPU architecture, OS, and Version:**

**Describe the bug**
ISOs generated can't be used as disks to boot directly from. 

**To Reproduce**
```
dd if=~/Downloads/cOS-Seed-green-0.8.2-5-gc8e7ede1-x86_64.iso of=test.img conv=notrunc
qemu-kvm -m 2048 -hda test.img
```
or boot the ISO as a volume from openstack.
**Expected behavior**
The system to boot

**Logs**
Boot is stuck after GRUB prompt
![Screenshot from 2022-02-25 10-27-21](https://user-images.githubusercontent.com/2420543/155692884-8d614744-747e-4d5b-9e45-9c386ef5f7af.png)

**Additional context**
https://github.com/Luet-lab/luet-makeiso/blob/master/pkg/burner/iso.go#L29
https://github.com/rancher-sandbox/os2/blob/master/ros-image-build#L69
https://rancher-sandbox.github.io/cos-toolkit-package-browser/cos-toolkit-green/live/grub2/0.0.2-1/

Ping also the Harvester team for the fix

**Comment by davidcassany** [comment]
I had a look to how KIWI handles the creation of hybrid images and it is far from obvious. A wide range of non obvious `-boot_image`  parameters are provided to xorriso tool. In addition it also provides an entry for an additional EFI partition to the partition table headers when read as disk. Here is a command example from KIWI:

```
xorriso \
    -application_id 0x5ac746a2 -publisher SUSE LINUX GmbH -preparer_id KIWI - https://github.com/OSInside/kiwi \
    -volid CDROM -joliet on -padding 0 -outdev (...)/test_hybrid_iso/tumbleweed.x86_64-1.99.1.iso \
    -map (...)/test_hybrid_iso/live-media.wp7zk8m9 / -chmod 0755 / -- \
    -boot_image grub bin_path=boot/x86_64/loader/eltorito.img \
    -boot_image grub grub2_mbr=(...)/test_hybrid_iso/live-media.wp7zk8m9/boot/x86_64//loader/boot_hybrid.img \
    -boot_image grub grub2_boot_info=on \
    -boot_image any partition_offset=16 \
    -boot_image any cat_path=boot/x86_64/boot.catalog \
    -boot_image any cat_hidden=on \
    -boot_image any boot_info_table=on \
    -boot_image any platform_id=0x00 \
    -boot_image any emul_type=no_emulation \
    -boot_image any load_size=2048 \
    -append_partition 2 0xef (...)/test_hybrid_iso/efi-loader.cho0ovbq \
    -boot_image any next \
    -boot_image any efi_path=--interval:appended_partition_2:all:: \
    -boot_image any platform_id=0xef \
    -boot_image any emul_type=no_emulation
```

At a time when xorriso support was added to KIWI I remember Marcus struggled quite a lot figuring out these parameters and get managed to to do with the help of the upstream xorriso maintainers. I could see that `xorriso` man pages are damn extensive and with many details, I'd say that with the above example and with the man pages we should be ready achieve real hybrid isos. Changes are required into the `luet-makeiso` scope.

**Comment by mudler** [comment]
Out of curiosity, I've tried to burn an USB stick with one iso built from luet-makeiso with GRUB as boot loader, and with the dracut initramfs. The result is that I could not boot the system succesfully either, getting the same result. On the other hand, I've tried then to use syslinux/systemd-boot and get ahead booting, but it stops while loading the squashfs. Booting from EFI seems to work, but seems the system is not entirely functional - as I could not login with default user/pass, and cloud-init configs seems didn't kicked in.

This is tricky to say at least, because with the same syslinux/systemd-boot setup I am capable to burn USB stick and boot them with a custom initrd , which is not dracut based. ( Mocaccino ISOs don't use dracut, but they are functional when being booted from USB disks, and the procedure to build the ISO is the same, except for the GRUB setup)

**Comment by mudler** [comment]
I think this is directly related: https://github.com/harvester/harvester/issues/1959 , seems also harvester has specific docs around it too https://docs.harvesterhci.io/v1.0/install/usb-install/#when-booting-from-a-usb-installation-flash-drive-a-grub-_-text-is-displayed-but-nothing-happens

**Comment by tristan-cottam** [comment]
I'm facing the same issue on a BIOS-only system when booting from USB, but have not been able to test c3OS itself.

**Comment by mudler** [comment]
Still needs luet-makeiso to be bumped in repos
