### ISSUE TITLE
meta/cos-modules pulls in elemental-cli

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1157]
**Is your feature request related to a problem? Please describe.**
meta/cos-modules is supposed to bring in only the cos static bits which are not compiled binaries. This is used for example to bring the cos modules within other environments where the cli, or other golang components are built separately

**Describe the solution you'd like**
currently the installer package depends on the cli, which in turns makes meta/cos-modules to ship the elemental-cli binary. As before we didn't had a cli binary in golang, this was an oversight and a regression.

Besides the installer package should be actually deprecated, in order to do this gradually I would start off by splitting it in a separate package: one for the bash wrappers to provide backward compatibility, and for example a separate one to provide the system-upgrade-controller integration

**Describe alternatives you've considered**

**Additional context**

**Comment by Itxaka** [comment]
installer is mostly deprecated already, only the rebrand stuff is missing (and the suc-upgrade) IIRC

**Comment by mudler** [comment]
Seems also cos-deploy is still using cos.sh
