### ISSUE TITLE
Drop cos.sh script

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#1159]
This card is about dropping `packages/installer/cos.sh` script.

While working on #1144 I realized we do not have a proper plan/steps for that and we should. I believe we are really close to do it in terms of feature set. I believe we mostly miss a replacement for `cos-deploy` (only for few corner cases if we actually aim to support them).

I believe we should keep `cos-installer` and equivalent wrappers around elemental just for backward compatibility but get rid of `cos.sh` in `installer` package, we still have the backport if we need the old `cos.sh`.

AFAIK this is only going to affect Harvester, so I guess this should be coordinated with them, even we already had some discussions about it and the impact surface is really limited.

**Comment by mudler** [comment]
I think the wrapper should be enough for backward compatibility, the critical part for the Harvester team would be to re-wire the env variables in case they depended on some internal variable tweak. But as far as I could see there should be nothing else than cloud-init/config and partitioning layout arguments.
