### ISSUE TITLE
Provide a replacement for `cos-deploy`

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#1160]
Currently we do not have replacement for `cos-deploy` command in elemental and I think this is the last piece missing before we can actually drop `package/installer/cos.sh`.

So far by looking at the old command code and docs this command is expected to do the following:

* Sets active and passive from channel
* Sets active and passive from a docker image if this is provided with the `--docker-image` flag
* Does all the above regardless being booted from active, passive or recovery

If we add the `channel` source to `element reset` and we assume we only support this feature set when booting from recovery (this is the only use case we documented), then `elemental reset` would could be a drop in replacement to `cos-deploy`.

**Comment by Itxaka** [comment]
Wasn't cos-deploy already substituted by cos-install --docker-image?

**Comment by davidcassany** [comment]
> Wasn't cos-deploy already substituted by cos-install --docker-image?

Not really, `cos-deploy` after the `cos.sh` refactor was using `cos-install` which is I doubt was properly replacing `cos-deploy` as it was meant to be. Also `cos.sh install --no-format` was doing strange logic to support some of these cases, like not installing recovery image if booting from a squashfs recovery image, which makes no sense from the installer point of view and it also is also incomplete, since recovery can be without squashfs. Also `cos-deploy` was supposed to pull images from channel by default which is not the case for the installer.

**Comment by mudler** [comment]
> > Wasn't cos-deploy already substituted by cos-install --docker-image?
> 
> Not really, `cos-deploy` after the `cos.sh` refactor was using `cos-install` which is I doubt was properly replacing `cos-deploy` as it was meant to be. 

I think cos-deploy implementation is working overall, maybe edge cases were not covered. we use `cos-deploy` in our testing pipeline also to create aws images, and that is still working. 
After the merge, there is no difference anymore between deploy and install. they were virtually equivalent, deploy was just a thin wrapper around cos-install, which then allowed to do things like https://rancher-sandbox.github.io/cos-toolkit-docs/docs/getting-started/install/#installation-from-3rd-party-livecd-or-rescue-mediums. They were fused together as cos-deploy's difference with the installer was just the partitioning

> Also `cos.sh install --no-format` was doing strange logic to support some of these cases, like not installing recovery image if booting from a squashfs recovery image, which makes no sense from the installer point of view and it also is also incomplete, since recovery can be without squashfs. 

Can't find traces of this, install and deploy are the same. The only thing that --no-format is doing is preventing partitions to be created, assuming that labels are in the system: https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/installer/cos.sh#L386

> Also `cos-deploy` was supposed to pull images from channel by default which is not the case for the installer.

That became less relevant with time, as that feature lost importance when moving out to a Dockerfile based approach. But still that should work as the code beneath is shared with the installer

**Comment by davidcassany** [comment]
> Can't find traces of this, install and deploy are the same.

Correct and that's the problem, because they should not behave the same. The problem is here https://github.com/rancher-sandbox/cOS-toolkit/blob/b4924c9807ceee79ca9c7dc1a266af2f6e326474/packages/installer/cos.sh#L1491 I don't think this is correct from the installer PoV (something like that should be a config not a use case guess) and incomplete from the cos-deploy PoV, IMHO `recovery_boot` should have been used. I believe our cos-deploy tests were not actually checking cos-install vs cos-deploy differences, so I'd say that in non-squashfs tests cos-deploy was silently installing the recovery image too.

> That became less relevant with time, as that feature lost importance when moving out to a Dockerfile based approach. But still that should work as the code beneath is shared with the installer

Probably, I did not test if `cos-installer --no-format` without any further flag or custom environment variables pulls the `system/cos` image from the channel if channel config is there. But `elemental` is certainly not doing that. In fact this is the only reason preventing me of using `element reset` in the place of `cos-deploy`, adding channel support in `elemental reset` should not be difficult, since the logic is already there in upgrade. You are right that channels are not really relevant, all this came as `cos-deploy` usage is mostly documented around the use of channels and there is no obvious way to do the same with a single command in elemental. Given it is not hard to support it I would go for it, probably in the future channel use case turns to be useful.

**Comment by Itxaka** [comment]
I guess this ended up by being "add channel install to installer" only

**Comment by mudler** [comment]
I think also https://github.com/rancher-sandbox/cOS-toolkit/pull/1168 is related to it (@davidcassany are you on it, right?)

**Comment by davidcassany** [comment]
Yes related. My first attempt was to actually use `elemental reset` in place of `cos-deploy` and created #1168 for that. Then I faced an unrelated issue that might be the same @mudler saw in #1165.

In any case we are not overlapping with @Itxaka and rancher-sandbox/elemental#132 really helps on that. With it `elemental install --no-format` could be seen as a replacement too

**Comment by Itxaka** [comment]
cc @davidcassany  https://github.com/rancher-sandbox/elemental/pull/132 is merged so https://github.com/rancher-sandbox/cOS-toolkit/pull/1168 may be impacted
