### ISSUE TITLE
Verify automatic partition growing works

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1165]
Seems that parition growing doesn't work correctly. I've been testing it on ARM images which didn't growed the partition automatically, but should be the same mechanism for x86_64.

- Verify if the mechanism is working
- Create follow-ups if required

**Comment by Itxaka** [comment]
@mudler can you provide the config which you used?

**Comment by mudler** [comment]
> @mudler can you provide the config which you used?

sure! that's the one: https://github.com/c3os-io/c3os/blob/master/overlay/files/system/oem/11_persistency.yaml#L30 

Note, I've tested this on arm64 -  I'm not sure if on x86_64 this is functional

**Comment by davidcassany** [comment]
Note there is a test for x86 here https://github.com/rancher-sandbox/cOS-toolkit/blob/781cc657aa5ea16b8fe978b8d4bcd19740943db0/tests/installer/installer_test.go#L86-L131

Verifying this tests should be enough for x86.

**Comment by Itxaka** [comment]
with a system installed from the lastest master iso, booting from recovery and using a simplified config from the one @mudler provided I get a success...but the partition is not grown.

Seems like in the stage config the `Expand` is set to null, which Im guessing is wrong somehow?

```
Stage: {"Commands":null,"Files":null,"Downloads":null,"Directories":null,"If":"","EnsureEntities":null,"DeleteEntities":null,"Dns":{"Nameservers":null,"DnsSearch":null,"DnsOptions":null,"Path":""},"Hostname":"","Name":"Repart image","Sysctl":null,"SSHKeys":null,"Node":"","Users":null,"Modules":null,"Systemctl":{"Enable":null,"Disable":null,"Start":null,"Mask":null},"Environment":null,"EnvironmentFile":"","DataSources":{"Providers":null,"Path":""},"Layout":{"Device":{"Label":"COS_PERSISTENT","Path":""},"Expand":null,"Parts":null},"SystemdFirstBoot":null,"TimeSyncd":null,"Git":{"Auth":{"Username":"","Password":"","PrivateKey":"","Insecure":false,"PublicKey":""},"URL":"","Path":"","Branch":"","BranchOnly":false}} 
```

**Comment by Itxaka** [comment]
This is my simple config:

```
cos-recovery:~ # cat /oem/expand.yaml 
name: "Default deployment"
stages:
  rootfs.after:
    - name: "Repart image"
      layout:
        device:
          label: COS_PERSISTENT
        expand_partition:
```

And COS_PERSISTENT is the last partition on the disk:

```
/dev/loop0: TYPE="squashfs"
/dev/sda1: LABEL="COS_OEM" UUID="bc01184d-f9f7-488e-af43-5afe76c9a811" BLOCK_SIZE="1024" TYPE="ext4" PARTUUID="d0c3c558-01"
/dev/sda2: LABEL="COS_STATE" UUID="1464df24-6405-406b-a956-e07c59dd41a1" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="d0c3c558-02"
/dev/sda3: LABEL="COS_RECOVERY" UUID="b3274996-d20b-4c91-8c93-d12ec0330eaf" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="d0c3c558-03"
/dev/sda4: LABEL="COS_PERSISTENT" UUID="c30d4103-a794-433a-bcf6-86ef196c38e1" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="d0c3c558-04"

```

**Comment by davidcassany** [comment]
You have to provide at least a size to expand, this is the expected behavior

**Comment by Itxaka** [comment]
ok, seem that expand partition needs a size, I thought it wasnt!

**Comment by davidcassany** [comment]
Size `0` means use all dis

**Comment by Itxaka** [comment]
can confirm, with setting a size 0 or a number it works. Wontfix @mudler :P

**Comment by Itxaka** [comment]
ahh indeed, under the yip readme example is still there: https://github.com/mudler/yip/blob/master/README.md?plain=1#L570

`size: 0 or unset means all available free space`

**Comment by Itxaka** [comment]
https://github.com/mudler/yip/pull/36

**Comment by mudler** [comment]
its also part of our docs :sweat_smile: created a PR here https://github.com/rancher-sandbox/cos-toolkit-docs/pull/74
