### ISSUE TITLE
Separate Docker image for elemental-cli

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1167]
Having a separate docker image for the elemental-cli helps in the context of installing from 3rd party (https://rancher-sandbox.github.io/cos-toolkit-docs/docs/getting-started/install/#installation-from-3rd-party-livecd-or-rescue-mediums ) and to test locally.

This requires also to have a look at all the binaries required by elemental to be functional

**Comment by mudler** [comment]
@Itxaka I guess the only remaining bit here is to use it for 3rd party installs?

**Comment by Itxaka** [comment]
ouch, didnt knew there was a card for this. Indeed this should be completed as we now have a docker image with elemental and the required tools inside and its pushed to quay.

So only the docs and maybe a test is required for this. I would like to have a small test that only triggers when the dockerfile is changed to make sure we are not breaking it, maybe just an elemental install loop or something like that.

**Comment by Itxaka** [comment]
ah I guess, I didnt found it cause this is on cos-toolkit instead of elemental....

**Comment by Itxaka** [comment]
missing docs: https://github.com/rancher-sandbox/cos-toolkit-docs
