### ISSUE TITLE
Cleanup AWS AMI images

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1190]
Currently we keep all released images on AMI, even if those are old assets that are not really used anymore.

Let's keep only the latest AMI release for the moment

- [ ] Check out with Paul permissions to do that
- [ ] Update our cleanup policy in AWS

**Comment by Itxaka** [comment]
Looks like the lifecycle manager would delete the AMIs but would leave the snapshot arounds ¬_¬

**Comment by Itxaka** [comment]
LifeCycle manager seems like its a bit short on what we want, will explore using a custom script.
