### ISSUE TITLE
Test raw disk deploy fails

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1201]
Seems the test raw disk deploy started to fail recently:

```
• Failure [165.664 seconds]
cOS Recovery deploy tests
/Users/runner/work/cOS-toolkit/cOS-toolkit/tests/recovery-raw-disk/recovery_raw_disk_test.go:9
  after running recovery from the raw_disk image
  /Users/runner/work/cOS-toolkit/cOS-toolkit/tests/recovery-raw-disk/recovery_raw_disk_test.go:23
    uses cos-deploy to install [It]
    /Users/runner/work/cOS-toolkit/cOS-toolkit/tests/recovery-raw-disk/recovery_raw_disk_test.go:24

    Unexpected error:
        <*errors.withStack | 0xc0000b0d80>: {
            error: <*errors.withMessage | 0xc0000d92c0>{
                cause: <*ssh.ExitError | 0xc0000f1a80>{
                    Waitmsg: {status: 1, signal: "", msg: "", lang: ""},
                },
                msg: "\x1b[36mINFO\x1b[0m[2022-03-24T01:05:53Z] Starting elemental version v0.0.13           \nError: no device found\n\x1b[31mERRO\x1b[0m[2022-03-24T01:05:54Z] State partition 'COS_STATE' not found        \n",
            },
            stack: [0x12cefdd, 0x12d129a, 0x12d1280, 0x126d27a, 0x126cc45, 0x126c33b, 0x126f4a9, 0x126ee87, 0x1284e85, 0x1284ba5, 0x12843e5, 0x1286692, 0x1291ca5, 0x129196b, 0x12d0f65, 0x10dc202, 0x1069ca1],
        }
        INFO[2022-03-24T01:05:53Z] Starting elemental version v0.0.13           
        Error: no device found
        ERRO[2022-03-24T01:05:54Z] State partition 'COS_STATE' not found        
        : Process exited with status 1
    occurred

    /Users/runner/work/cOS-toolkit/cOS-toolkit/tests/recovery-raw-disk/recovery_raw_disk_test.go:28
------------------------------

```

**Additional context**
- https://github.com/rancher-sandbox/cOS-toolkit/runs/5668948084?check_suite_focus=true
- https://github.com/rancher-sandbox/cOS-toolkit/runs/5668591417?check_suite_focus=true
- https://github.com/rancher-sandbox/cOS-toolkit/runs/5668740862?check_suite_focus=true
- https://github.com/rancher-sandbox/cOS-toolkit/runs/5684036928?check_suite_focus=true

**Comment by davidcassany** [comment]
Found the bug. Even I can't explain it did not pop up until now. The issue is related to the partitioner or, more specific, to the yip plugin that makes use of the partitioner. I am about to fix it, the is issue is that parted does not extend the partition table if it does not match with the current device (some image got dd'ed to a bigger disk), in such case it throws an error when creating a new partition unless it is fixed before hand. This is something I missed to port on the elemental reimplementation of the plugin.

**Comment by davidcassany** [comment]
Requires the elemental bump still
