### ISSUE TITLE
`elemental build-iso`: port code from `luet-makeiso`

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1217]
This card is about to port required portions from https://github.com/Luet-lab/luet-makeiso tailored to our needs in `elemental` as `build-iso` command option.
This will free from external dependencies during the ISO build process
## Action items

- [x] port current makeiso code to elemental and adapt it as needed, or use it just as a base for inspiration (as you see fit)

In the elemental-cli, we need to customize the following aspects during iso build which needs customization on top of current code:
- [ ] ~we can imply default grub configuration and offer a simple switching to syslinux (if we want to support it still?)~ No syslinux support for the time being. We should address https://github.com/rancher-sandbox/elemental/pull/160#issuecomment-1096299621 first to find a reasonable way to outline the bootloader specific config details somewhere else.
- [x] we can automatically fill in the repository url, and exposing just the uri as parameter to the user in case of override
- [x] drop usage of luet as external binary, as `elemental` cli has capabilities to call it already internally
- [x] we can automatically fill the required package set for iso, and still offering an override mechanism 
- [ ] adapt `os2` and `cOS` to build ISOs with `elemental`, and drop the dependency to makeiso (also from cOS repositories) #1245 rancher-sandbox/os2#96
- [x] Adapt docs  rancher-sandbox/cos-toolkit-docs#82
- [x] Ping harvester team to make them aware of breaking changes, if any.

**Comment by mudler** [comment]
> do we have to maintain backwards compatibility with the iso.yaml/manifest.yaml of the existing makeiso? Expand it?

I'd say so in case of overrides. Ideally `elemental build-iso` should take just a container image as argument, and all other options should be optional and overrideable also via cli args ( e.g. overlay dir, hybrid images, etc ).

What we want to achieve here is minimal user interaction as 99% of times default values are just fine (e.g. calling just `elemental build-iso $IMAGE`. The most used tweaked options are the iso overlay rootfs and the container image.

**Comment by Itxaka** [comment]
Maybe investigate https://github.com/kdomanski/iso9660 while creating this, because we could may get away with using a pure golang lib....

**Comment by Itxaka** [comment]
seems like https://github.com/diskfs/go-diskfs also allows for iso creation supporting eltorito extensions...

**Comment by mudler** [comment]
> seems like https://github.com/diskfs/go-diskfs also allows for iso creation supporting eltorito extensions...

note that's exactly the one that was used by makeiso previously, we went back at using standard tooling. The library didn't quite fit all our scenarios, e.g. for hybrid ISO #1148

**Comment by Itxaka** [comment]
blargh, thats a shame then :/

**Comment by agracey** [comment]
As part of the docs, showing how to limit resource consumption would be nice. I'd rather not crash windows from WSL again :D
