### ISSUE TITLE
rancher-sandbox/luet-mtree has potential security vulnerabilities in its dependencies.

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/cOS-toolkit#1223]

**Comment by Itxaka** [comment]
not sure if this is real @kkaempf 

See https://github.com/dependabot/dependabot-core/issues/4740 this is wrongly reporting entries in go.sum as dependencies, which is not correct.

**Comment by Itxaka** [comment]
Updated deps and seems like all alerts have been auto closed: https://github.com/rancher-sandbox/luet-mtree/security/dependabot?q=is%3Aopen

https://github.com/rancher-sandbox/luet-mtree/pull/10

**Comment by jeffwidman** [comment]
BTW, GitHub fixed it so `go.sum` is no longer used as a source of dependencies: https://github.blog/changelog/2023-03-07-dependency-graph-removes-go-sum-support/
