### ISSUE TITLE
`elemental build-disk`: port current raw_disk image and arm scripts

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1227]
This card is about to port required scripts from https://github.com/rancher-sandbox/cOS-toolkit/tree/master/images as `elemental build-disk` command option.

## Action items

- [x] port current scripts logic in go (img, gce, azure, aws, arm) (most of them are similar, with just few exceptions from one to another)
- [x] we can imply sane defaults to the user, ideally customizable
- [x] we can automatically fill in the repository url, and exposing just the uri as parameter to the user in case of override
- [x] drop usage of luet as external binary, as `elemental` cli has capabilities to call it already internally
- [x] adapt `os2` and `cOS` to build disks with `elemental`
- [x] Adapt docs
- [x] Ping harvester team to make them aware of breaking changes, if any.

**Comment by Itxaka** [comment]
https://github.com/rancher-sandbox/elemental/pull/171

**Comment by Itxaka** [comment]
> we can imply sane defaults to the user, ideally customizable
> we can automatically fill in the repository url, and exposing just the uri as parameter to the user in case of override

Both of this are not filled, and I dont think it should be part of elemental to provide those. We can ship a default manifest.yaml or an example one, but users should provide their own with the proper configs set, either based on the default one or a custom one like currently. Not really liking all this override defaults by flags, when we cna have a nice, tracked, git diffed, with history, config file.

**Comment by Itxaka** [comment]
https://github.com/rancher-sandbox/elemental/pull/174 to provide default errors only overridable via config file

**Comment by Itxaka** [comment]
cos-toolkit: https://github.com/rancher-sandbox/cOS-toolkit/pull/1261

**Comment by Itxaka** [comment]
For os2, afaik it doesnt produce vanilla images, only final images so this is not required to be updated in that repo

**Comment by Itxaka** [comment]
Docs: https://github.com/rancher-sandbox/cos-toolkit-docs/pull/83

**Comment by Itxaka** [comment]
@bk201 We are also changing the way we build the raw/recovery images to rely on elemental instead of the current scripts at https://github.com/rancher-sandbox/cOS-toolkit/tree/master/images

AFAIK harvester doesnt use any of this scripts currently, they just build iso images which means that you shouldnt be affected by this. 

Could you confirm this please? Thanks!

**Comment by bk201** [comment]
@Itxaka That's correct, we just build ISOs with luet-makeiso. Thanks!
