### ISSUE TITLE
ARM qemu builds are constantly failing

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1240]
This seems to happen since a while now, and packages aren't being published since a while indeed: 

https://github.com/rancher-sandbox/cOS-toolkit/runs/6035384004?check_suite_focus=true

Seems the suite is timing out

**Comment by Itxaka** [comment]
Also seems not to build properly, claiming that elemental cannot be found ???


```
 INFO   #11 0.488 /bin/sh: elemental: command not found
```

**Comment by Itxaka** [comment]
currently the problem seems to be that latest elemental package was not published for arm64, so the arm64 build is trying to use elemental but getting an older package which doesnt contain half of the functionality

**Comment by mudler** [comment]
> currently the problem seems to be that latest elemental package was not published for arm64, so the arm64 build is trying to use elemental but getting an older package which doesnt contain half of the functionality

yup, this applies to several packages, luet included. the version is quite old and the tree doesn't build with that version ( https://github.com/rancher-sandbox/cOS-toolkit/pull/1265#issuecomment-1112138968 )

**Comment by Itxaka** [comment]
first job to fail which should have published more moder packages is at https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/2097692983

This is all github CI issues, it cant download the build results somehow, so it times out trying to get artifacts :/

**Comment by Itxaka** [comment]
at worst, I can manually build the packages on the worker and publish them directly so we can avoid this current blocker :/

**Comment by mudler** [comment]
@Itxaka that was my first thought, we can also disable all tests on the pipeline. I'm actually refining a bit the pipeline in here #1259 to be able to use the upstream binaries on-need. Maybe I should split it up in its own PR so we can use it to push things?

**Comment by Itxaka** [comment]
sounds good to me.

Im also checking to retry the first job that originally failed. If that is able to push the packages correctly, we may be able to trigger a couple of jobs more in order to push newer packages, i.e. luet, so those are finally there and ready for the next jobs

**Comment by mudler** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/2239563428 should be publishing (once being picked up)

**Comment by Itxaka** [comment]
umm actually, packer cant ssh into the machine, even when the machine boots correctly and has ssh up and running

**Comment by Itxaka** [comment]
wow, instance has no network somehow? No ip on eth0 ¬_¬

**Comment by mudler** [comment]
> wow, instance has no network somehow? No ip on eth0 ¬_¬

mh. tricky, is there the network cloud init under `/system/oem`?

**Comment by Itxaka** [comment]
yep yep, the link is up, but no IP attached!! the config seems correct, wtf

**Comment by mudler** [comment]
now arm64 builds are fixed (not QEMU)

**Comment by Itxaka** [comment]
just tested on a qemu vm the iso from https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/2238805215 the latest run with the latest artifacts.

It boots correctly.
cos-setup-X services run correctly.
eth0 is up.
ifcfg-eth0 is correctly configured with the oem values
eh0 has the correct ip :ok_hand: 


Launching the same iso with packer:

It boots correctly.
cos-setup-X services run correctly.
eth0 is up.
ifcfg-eth0 is correctly configured with the oem values
eth0, no ip :-1: 

Seems like dhcp requests are failing:
![image](https://user-images.githubusercontent.com/1447686/165837313-84b85b5a-dbb4-4d6e-9a0f-0e27510c7a79.png)

So this seems to be a qemu problem somehow...

**Comment by Itxaka** [comment]
interestingly enough, I cant reproduce this with packer 1.7.3, but Ic an with packer 1.8.0, which is the exact version on github....so it poitns to either a problem with packer or the qemu plugin. seeing that the qemu plugin was pinned in version 1.7.9 (January 19, 2022) it may come from there. Gonna test with older versions to see if its reproducible

**Comment by Itxaka** [comment]
This fix for efi firmware could also affect us ¬_¬

**Comment by Itxaka** [comment]
Looks like indeed the problem comes from a newer package version, pinning it to a know working version (1.7.3) makes it work again with no other changes.

Will look at it in deep next week, probably open a bug upstream to see if there is a problem there

**Comment by Itxaka** [comment]
New problem, yq is installed for the wrong architecture somehow?

https://github.com/rancher-sandbox/cOS-toolkit/runs/6256092995?check_suite_focus=true

```
Run sudo -E MAKEISO_ARGS="--name cOS-Seed-green--g80d0fc7e-arm64 --repo quay.io/costoolkit/releases-green-arm64" make local-iso
/bin/sh: 1: yq: Exec format error
/bin/sh: 1: yq: Exec format error
/usr/bin/elemental --debug --config-dir /home/runner/work/cOS-toolkit/cOS-toolkit build-iso --name cOS-Seed-green--g80d0fc7e-arm64 --repo quay.io/costoolkit/releases-green-arm64 --date --repo /home/runner/work/cOS-toolkit/cOS-toolkit/build
/usr/bin/elemental: 1: Syntax error: ")" unexpected
make: *** [make/Makefile.iso:81: local-iso] Error 2
```

Package on deps_ci target are installed from wrong repo in arm64:

```
  INFO   Packages that are going to be installed in the system:

Program Name                       | Version    | License       | Repository
toolchain/luet-mtree-0.0.9-2       | 0.0.9-2    |               | cos       
toolchain/yq-4.25.1                | 4.25.1     | MIT           | local     
toolchain/elemental-cli-0.20220501 | 0.20220501 |               | local     
meta/cos-verify-0.10-1             | 0.10-1     |               | cos       
toolchain/cosign-1.4.1-8           | 1.4.1-8    |               | cos       
toolchain/luet-cosign-0.0.11-2     | 0.0.11-2   |               | cos       
utils/jq-1.6-30                    | 1.6-30     | MIT CC-BY-3.0 | cos       

 INFO   Copying file yq-toolchain-4.25.1.package.tar.zst from /home/runner/work/cOS-toolkit/cOS-toolkit/build
 INFO   Copying file elemental-cli-toolchain-0.20220501.package.tar.zst from /home/runner/work/cOS-toolkit/cOS-toolkit/build
 INFO   SUCCESS 📦  Package  toolchain/yq-4.25.1 downloaded
 INFO   Downloading image quay.io/costoolkit/releases-green:cos-verify-meta-0.10-1
 INFO   SUCCESS 📦  Package  toolchain/elemental-cli-0.20220501 downloaded
 INFO   Downloading image quay.io/costoolkit/releases-green:cosign-toolchain-1.4.1-8
 INFO   Image: quay.io/costoolkit/releases-green:cos-verify-meta-0.10-1. Pulled: sha256:520ac6ebc24c0ce2dc85d6b3cb88b554d2bd1f33082e2eb1efdd2dbb85329e3a. Size: 0B
 INFO   SUCCESS 📦  Package  meta/cos-verify-0.10-1 downloaded
 INFO   Downloading image quay.io/costoolkit/releases-green:luet-cosign-toolchain-0.0.11-2
 INFO   Image: quay.io/costoolkit/releases-green:luet-cosign-toolchain-0.0.11-2. Pulled: sha256:c781297a10c698cc0f4b1656280d68a2efd53c37bdd124580de532326703baf0. Size: 3.25MiB
 INFO   SUCCESS 📦  Package  toolchain/luet-cosign-0.0.11-2 downloaded
 INFO   Downloading image quay.io/costoolkit/releases-green:jq-utils-1.6-30
 INFO   Image: quay.io/costoolkit/releases-green:jq-utils-1.6-30. Pulled: sha256:71be51199c79cb2e673b87e447eb92093b3511c287156906ec65a5d481f85912. Size: 1.967MiB
 INFO   SUCCESS 📦  Package  utils/jq-1.6-30 downloaded
 INFO   Downloading image quay.io/costoolkit/releases-green:luet-mtree-toolchain-0.0.9-2
 INFO   Image: quay.io/costoolkit/releases-green:luet-mtree-toolchain-0.0.9-2. Pulled: sha256:e9c729ad9b4ef88fc7094550da47b1741de82b7b5eae2874a3cf128692f04a4e. Size: 17.77MiB
 INFO   Image: quay.io/costoolkit/releases-green:cosign-toolchain-1.4.1-8. Pulled: sha256:ec96aad87ea61fb5c02267570e11d635f0f367b2e8f5e86d8e1515ee6d2e6f9b. Size: 79.98MiB
 INFO   SUCCESS 📦  Package  toolchain/luet-mtree-0.0.9-2 downloaded
 INFO   SUCCESS 📦  Package  toolchain/cosign-1.4.1-8 downloaded
```

**Comment by Itxaka** [comment]
Looks like deps_ci is not exporting the LUET_ARCH value correctly so its installing x86 stuff and repos

**Comment by Itxaka** [comment]
Looks like in the end the error came out from an outdated packer-plugin-qemu. Latest 1.0.3 version of the plugin fixes things, but the latest packer version (1.8.0) comes with an older version. Installing it manually causes other issues so we can wait for the next packer version that bumps the plugin so its bundled.

**Comment by Itxaka** [comment]
nwo some tests failing, probably due to https://github.com/rancher-sandbox/elemental/issues/184 as it fails during luet package install due /tmp being exhausted:

`ERROR     Failed storing package quay.io/costoolkit/releases-green-arm64:cos-system-0.8.9-20 from cache: write /tmp/cachepkgs1375713205`

Full log:


```
Program Name | Version  | License | Repository
          system/cos   | 0.8.9-20 |         | cos       
          
           INFO    Downloading image  quay.io/costoolkit/releases-green-arm64:cos-system-0.8.9-20
           INFO    Image: quay.io/costoolkit/releases-green-arm64:cos-system-0.8.9-20. Pulled: sha256:083d78ba6786108b31368703f64d8fdd7385febf584674f51f2258e967cfe1cd. Size: 840.3MiB
            ERROR     Failed storing package quay.io/costoolkit/releases-green-arm64:cos-system-0.8.9-20 from cache: write /tmp/cachepkgs1375713205/57/571b197a6152492d675d416d2a945acc143064c48c6215a0dc5159ba6abe7aabf2d182bcf83e6fb38b23ebf36e8f70be1731f40dacc3cff4e52c5d295b8cc9a6-d: no space left on device
          panic: runtime error: invalid memory address or nil pointer dereference
          [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x96f4c8]
          
          goroutine 78 [running]:
          github.com/mudler/luet/pkg/api/core/types/artifact.(*Checksums).generateSum(0x40003d9cc0, 0x0?, {{0x1120fe8?, 0x40139a8c00?}, {0xecc3de?, 0x4000000000?}})
          	/luetbuild/go/pkg/mod/github.com/mudler/luet@v0.0.0-20220127164253-6f77fa2b3a72/pkg/api/core/types/artifact/checksum.go:78 +0x48
          github.com/mudler/luet/pkg/api/core/types/artifact.(*Checksums).generateSHA256(0x0?, 0x0?)
          	/luetbuild/go/pkg/mod/github.com/mudler/luet@v0.0.0-20220127164253-6f77fa2b3a72/pkg/api/core/types/artifact/checksum.go:73 +0x5c
          github.com/mudler/luet/pkg/api/core/types/artifact.(*Checksums).Generate(...)
          	/luetbuild/go/pkg/mod/github.com/mudler/luet@v0.0.0-20220127164253-6f77fa2b3a72/pkg/api/core/types/artifact/checksum.go:60
          github.com/mudler/luet/pkg/api/core/types/artifact.(*PackageArtifact).Verify(0x0)
          	/luetbuild/go/pkg/mod/github.com/mudler/luet@v0.0.0-20220127164253-6f77fa2b3a72/pkg/api/core/types/artifact/artifact.go:112 +0x70
          github.com/mudler/luet/pkg/installer.(*LuetInstaller).getPackage(0x4000688a80?, {0x40264f7cc0?, 0x4007af37a0?, {0x111d170?, 0x401eb04480?}}, {0x112a0b0?, 0x4028f3c380?})
          	/luetbuild/go/pkg/mod/github.com/mudler/luet@v0.0.0-20220127164253-6f77fa2b3a72/pkg/installer/installer.go:947 +0x68
          github.com/mudler/luet/pkg/installer.(*LuetInstaller).downloadWorker(0x400061d300, 0x40005b3900?, 0x40005c0d80?, 0x0, 0x0?, {0x112a0b0, 0x4028f3c380})
          	/luetbuild/go/pkg/mod/github.com/mudler/luet@v0.0.0-20220127164253-6f77fa2b3a72/pkg/installer/installer.go:981 +0xb4
          created by github.com/mudler/luet/pkg/installer.(*LuetInstaller).download
          	/luetbuild/go/pkg/mod/github.com/mudler/luet@v0.0.0-20220127164253-6f77fa2b3a72/pkg/installer/installer.go:638 +0x3dc
          : Process exited with status 2
      occurred

      /home/runner/work/cOS-toolkit/cOS-toolkit/tests/upgrades-images-signed/upgrade_test.go:32
```

**Comment by Itxaka** [comment]
last PR https://github.com/rancher-sandbox/cOS-toolkit/pull/1303 fixed the tests.
