### ISSUE TITLE
Generate image checksums during build time

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/cOS-toolkit#126]
This is a follow up of https://github.com/rancher-sandbox/cOS-toolkit/issues/107 which was a spike.

Looks like its possible to create such utility and would be helpful to implement as its needed as part of https://github.com/rancher-sandbox/cOS-toolkit/issues/95

See https://github.com/vbatts/go-mtree for a working utility that already does this.

### Requirements
 - [x] Accepts a dir and generates a checksum
 - [x] Accepts a dir and a checksum file and compares it
 - [x] plugin for luet based of luet-mtree https://github.com/Itxaka/luet-mtree
 - [x] generate the checksums during the build process https://github.com/rancher-sandbox/cOS-toolkit/pull/166
 - [x] Push the checksums (along the image? as part of metadata?)

**Comment by davidcassany** [comment]
Up to my understanding our mandatory need and primary use case is to validate the installation and upgrade process, meaning we should be capable to compare the installed/upgraded filesystem with the downloaded image. For that I assume we will use this tool inside the upgrade and installation scripts. So I don't see the need of comparing two files for now, I would drop that as a requirement for now.

**Comment by mudler** [comment]
Yes, to add on top, we should just be able to hash what gets into this phase: https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/installer/upgrade.sh#L116 which is basically unpacking the content from a docker image. 

What we need to be able to get from the CLI is the hash of the content of what's in `/tmp/upgrade` in our case, after we have pulled the content, or even better by reading the img file after it gets umounted, so we can verify directly the generated image files also outside the upgrade context (e.g. a user could verify an image that is being used currently at boot, by comparing the hashes with the one provided by us)

**Comment by Itxaka** [comment]
luet plugin has been created at https://github.com/Itxaka/luet-mtree which currently allow to generate and check a file/dir against a mtree-based checksum file

**Comment by mudler** [comment]
@Itxaka I think we can close this one, right? https://github.com/rancher-sandbox/cOS-toolkit/pull/179 was merged, I'm opening a new issue to track the CLI work separately

**Comment by Itxaka** [comment]
Indeed! Now that we push it along the metadata, this part is finished!
