### ISSUE TITLE
elemental build-iso: `--local` flag to pick-up images from docker daemon

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1279]
Currently elemental build-iso doesn't load images from the local docker daemon (as previously `luet-makeiso` was capable of), breaking the development workflow https://github.com/rancher-sandbox/elemental/blob/edc412b0dd1c219a07e023d16cafb6251f7280cd/pkg/elemental/elemental.go#L337

This card is about to port back that functionality to `elemental build-iso`

**Comment by davidcassany** [comment]
What about making it default behavior for luet unpack? Something like, try to load local daemon first and if not there then pull from from the registry. We could also extend luet interface to be capable of explicit local, explicit remote and try local first. What you think? This could prevent us from having to use a `--local` flag. Also could allow us to define a new source type like `docker-dameon` to force explicit local images.
