### ISSUE TITLE
'make clean' leaves isowork/overlay

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#128]
`isoworks/overlay` uses 842MB on my system and should be removed by `make clean`

**Comment by mudler** [comment]
Since https://github.com/rancher-sandbox/cOS-toolkit/pull/56 was merged, this shouldn't be an issue anymore. @kkaempf can you confirm?

**Comment by kkaempf** [comment]
Confirmed, thanks !
