### ISSUE TITLE
elemental build-iso: wrong repo priority order

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1282]
Seems that during the PR builds while building the iso we are picking up the wrong repository priority order, and as a result PR and CI are testing remote packages than the local changes.

See e.g. : https://github.com/rancher-sandbox/cOS-toolkit/pull/1276

**Comment by davidcassany** [comment]
Looks like I coded the local-iso and non local iso targets with swaped config https://github.com/rancher-sandbox/cOS-toolkit/blob/80d0fc7e67b43f4764d7ccd51b834b8f7261e304/.github/workflows/build-pr-green-x86_64.yaml#L147-L154

Note I added the final repo into the local-iso build not to the remote one... my bad 🙏🏽
