### ISSUE TITLE
arm64: fails in upgrading tests

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1288]
Seems somehow the default channel repository for arm is not getting the dashes correctly:

https://github.com/rancher-sandbox/cOS-toolkit/runs/6232507333?check_suite_focus=true

**Comment by Itxaka** [comment]
Looks like its really coming from the cos-config package, booting from the iso:

![image](https://user-images.githubusercontent.com/1447686/166432090-74f2497e-7955-4200-8872-c824cdda2e37.png)

**Comment by Itxaka** [comment]
it goes deeper lmao, if you bring the latest quay.io/costoolkit/releases-green-arm64:upgrades-cloud-config-0.1-2 package, the repo is correct in there.....

**Comment by Itxaka** [comment]
but on quay.io/costoolkit/releases-green-arm64:cos-system-0.8.9-16 which should depend on quay.io/costoolkit/releases-green-arm64:upgrades-cloud-config-0.1-2 the repo is wrong...

**Comment by mudler** [comment]
To note, in https://github.com/rancher-sandbox/cOS-toolkit/runs/6232098125?check_suite_focus=true, caused by #1282  the ISO contained the remote image, not the one currently built, so things gets quite messy.

**Comment by Itxaka** [comment]
0.8.7-17 was the latest working image with the proper repo url. Afterwards the build process was broken and nothing was published until https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/2239563428 which published system/cos-0.8.9-15 which was already broken. That same job also published cloud-config/upgrades-0.1-2.

**Comment by mudler** [comment]
the issue seems to be that the meta is selected, but the meta is containing the yaml files overriding the ones coming from the packages: https://rancher-sandbox.github.io/cos-toolkit-package-browser/cos-toolkit-green-arm64/system/cloud-config/0.11-1/

#1291 should fixup the issue, seems also that version of cloud-config is not in the tree, so somehow we must have bumped that accidentally

**Comment by Itxaka** [comment]
Now the problem has changed to: "Cant build proper arm64 isos from x86 hosts" as we pass no repo, the default repo is the x86 so the not built package, i.e. grub ones, are installed from the x86 repo.

We discussed this already with @davidcassany about adding an --arch to the iso command. Meanwhile we can try to build the iso in arm64 nodes...maybe?

**Comment by Itxaka** [comment]
nah, same problem.

I think that beforehand we used to always build the local needed packages by using the manifest.yaml to gather the needed local packages (PACKAGES on the makefile), but now with the new build.go stuff, we just build the packages that are missing on the repo, so we will always get some packages from a remote repo.

A workaround can be implemented to either add the repo (testing that now) or maybe we can force building always the needed packages for an iso (grub/live/etc...) so they live on the local repo.

**Comment by mudler** [comment]
> 
> I think that beforehand we used to always build the local needed packages by using the manifest.yaml to gather the needed local packages (PACKAGES on the makefile), but now with the new build.go stuff, we just build the packages that are missing on the repo, so we will always get some packages from a remote repo.

The build.go stuff isn't much new, the real thing here is that we read the manifest for the repos, but before we were actually writing a manifest for it to run. The manifest contained the repositories with the correct prios, so you would get tests only of the packages that changed in the local build

> 
> A workaround can be implemented to either add the repo (testing that now) or maybe we can force building always the needed packages for an iso (grub/live/etc...) so they live on the local repo.

My suggestion here would be to simply move the jobs to the arm64 architecture. the ISO build don't take that long (shouldn't)

**Comment by Itxaka** [comment]
> My suggestion here would be to simply move the jobs to the arm64 architecture to the arm runner, at least for now until elemental knows about archs. the ISO build don't take that long (shouldn't)

The problem with this is that we currently have 4 arm jobs, which already take a toll in our single arm worker. Adding the iso build to the arm workers adds 25 minutes per job of blocked arm worker, which is quite a lot :/

**Comment by Itxaka** [comment]
Up to https://github.com/rancher-sandbox/cOS-toolkit/commit/8315e5ef333553537f6f12b9f14a152432105068 package were build with the wrong repo. 

So packages between 0.10-2 and 0.10 (included) were broken.

Now I have no idea why its not picking the latest package for that, as we got several fixed ones afterwards....

**Comment by Itxaka** [comment]
as the --arch fix was merged on elemental and published under cos-toolkit. moving to use that to build the isos so we can avoid the remote fetching on arm64 and the wrong fetching of different arches.

**Comment by Itxaka** [comment]
with https://github.com/rancher-sandbox/cOS-toolkit/pull/1293 it now works
