### ISSUE TITLE
default tmpdir for luet is /tmp which can cause out of space errors

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/cOS-toolkit#1302]
Seems like we dont ship the luet config with a tmpdir_base: "/var/tmp/luet" config like with do with our get_luet.sh script, which means that it gets the default /tmp value.

In cOS, the /tmpdir is a tmpfs with a value of 25% of the physical memory. This means that on low memory devices, the /tmp dir can be exhausted easily if memory usage is low, as that would fill all the available memory and wont allow writing to /tmp, as it run out of space.

Mixing this with some of our repo meta files, which are on excess of 300Mb means that it we can hit this at any time, and we actually are hitting this on arm64 CI if we lower the VM machine to 4096 (Maybe arm64 binaries are more memory hungry?). And if our meta yaml keep growing its just a matter of time until we hit this on x86.

Not sure what the fix is here, for the meta yaml there is already a bug open, but maybe we should set the luet tmpdir to a different value, like the COS_PERSISTENT if it exists? We do it like that on the upgrade command.

**Comment by mudler** [comment]
being consistent is good, so on my side expectations would be to follow the same pattern for elemental upgrades. so if someone specifies a tempdir we can respect that, but makes sense to have sane default values that don't need a workaround by themselves (we don't want people to care about setting a tmpdir,no?)

**Comment by Itxaka** [comment]
Well, /tmp is kind of a sane default, isnt it? Like standard for temp files.... but yes, a generic method for obtaining a place where to put the tmp files in a system like cos, in which /tmp can be really restricted, makes sense. Then we could use it everywhere to forget about it and specially to have the same thing over all commands, so we dont have problems with different commands here and there due to this.

**Comment by Itxaka** [comment]
mmmh, this was fixed already by setting a proper tmpdir and cachepkg dir on elemental, so closing
