### ISSUE TITLE
Discover shebangs in user-data, so we handle them as executable scripts

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#139]
In  `datasource` plugin of yip we should interpret when the user-data content is a shell script or python script or whatever by check the existence or not of shebang.

If shebang is there we should copy it to the provided path, make it executable and eventually execute it?

**Comment by kkaempf** [comment]
> If shebang is there we should copy it to the provided path, make it executable and eventually execute it?

That was my understanding from yesterday's conversation. However, I'm not sure if there's always a path provided.

**Comment by davidcassany** [comment]
> That was my understanding from yesterday's conversation. However, I'm not sure if there's always a path provided.

Regarding the path, the plugin uses `/run/config` folder as default if not path is provided.
