### ISSUE TITLE
Explore go-mtree checks including SELinux labels

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#147]
We should explore if go-mtree allows us to consistently check a rootfs-tree including, at least, the xattr that are devoted to SELinux.

The idea is to be capable to recreate the SELinux labels at any time and still keep the go-mtree result stable and consistent, so we can eventually check if they are not properly applied.

The use case is to: 

1. Store the go-mtree results from a rootfs including SELinux Labels
2. Pack the rootfs into a container image (we loose xattr info in that process)
3. Upack the container including the rootfs into a filesystem
4. Re-apply the SELinux labelling
5. Check if go-mtree is consistent over the recently extracted rootfs compared with the check on step 1

Related to #135 and #22

**Comment by davidcassany** [comment]
The described procedure works, the issue I found is that `luet install` seams to include some cache in `/var/cache/luet` and even the cache is equivalent for two executions from the same exact repository the timestamps do not match. I could not find a combination of flags and configs that prevents that to happen. I tested with a repository setup such as:

```yaml
repositories:
  - name: localrepo
    enable: true
    urls:
      - /root/repo
    type: disk
    cached: false
```

This is the experiment I did in a Leap 15.3 VM that has SELinux tools installed (required to relabel).

```bash
# install cos rootfs from PR#135 in to /root/testroot folder
> luet install --system-target /root/testroot --system-engine memory -y system/cos

# apparently luet set some cache I could not get rid of, deleting it
> rm -rf testroot/var/cache/luet

# no SELinux labels are set after installing the system/cos package
> ls -Z testroot/
? bin  ? boot  ? dev  ? etc  ? home  ? lib  ? lib64  ? mnt  ? oem  ? opt  ? proc  ? root  ? run  ? sbin  ? selinux  ? srv  ? sys  ? system  ? tmp  ? usr  ? var

# relabel the root tree under /root/testroot
> TARGET=/root/testroot
> setfiles -r ${TARGET} ${TARGET}/etc/selinux/targeted/contexts/files/file_contexts ${TARGET}

# SELinux labels are now applied
> ls -Z testroot/
       system_u:object_r:bin_t:s0 bin          system_u:object_r:lib_t:s0 lib       system_u:object_r:default_t:s0 proc            system_u:object_r:var_t:s0 srv            system_u:object_r:var_t:s0 var
      system_u:object_r:boot_t:s0 boot         system_u:object_r:lib_t:s0 lib64  system_u:object_r:admin_home_t:s0 root          system_u:object_r:sysfs_t:s0 sys
    system_u:object_r:device_t:s0 dev          system_u:object_r:mnt_t:s0 mnt       system_u:object_r:var_run_t:s0 run         system_u:object_r:default_t:s0 system
       system_u:object_r:etc_t:s0 etc      system_u:object_r:default_t:s0 oem           system_u:object_r:bin_t:s0 sbin            system_u:object_r:tmp_t:s0 tmp
 system_u:object_r:home_root_t:s0 home         system_u:object_r:usr_t:s0 opt                                    ? selinux         system_u:object_r:usr_t:s0 usr

# compute an mtree manifest including xattr
> gomtree -c -K xattrs -p /root/testroot/ > ~/root_after_labels.mtree

# install the cor rootfs to some other directory and repeat the process
> luet install --system-target /root/testnewroot --system-engine memory -y system/cos
> rm -rf testnewroot/var/cache/luet

> TARGET=/root/testnewroot
> setfiles -r ${TARGET} ${TARGET}/etc/selinux/targeted/contexts/files/file_contexts ${TARGET}

> gomtree -c -K xattrs -p /root/testnewroot/ > ~/newroot_after_labels.mtree

# check the manifest form /root/testnewroot against /root/testroot
> gomtree -K xattrs -p /root/testroot/ -f ~/newroot_after_labels.mtree                           
"var/cache": keyword "time": expected 1620210584.637106465; got 1620210580.153086983
".": keyword "time": expected 1620210349.772085684; got 1620210151.891225640
FATA[0004] mainfest validation failed
```

The check fails because of the mentioned changes in /var/cache/luet that are applied beyond container image extraction. To fully verify the procedure I did another execution of the above procedure but excluding the `time` keyword from the mtree manifest and adding `sha512digest` as an alternative not make the check too relaxed and I got successful results. IMHO we should always use both, `sha512digest` and `time` keywords for verification beyond `xattr` and the other defaults. Indeed I think a reasonable list of keywords for our use case could be: `type,nlink,mode,uid,gid,size,xattr,link,sha512digest,time`

@Itxaka I think the above is relevant for #126.

Regarding the luet issue to my eyes we are missing more fine grained control to what `--system-target` flag gives us. To my eyes the distinction of `--root` and `--installroot` that for instance `zypper` has is meaningful to this kind of use cases. Would be nice if there was a way to state the installation, but only the installation, should happen to an alternate root, however the config, cache and all other interactions luet has with the files system would be based on the current root.

I also could not manage to actually use `luet util unpack` form a local tarball image/package.

**Comment by mudler** [comment]
> Regarding the luet issue to my eyes we are missing more fine grained control to what `--system-target` flag gives us. To my eyes the distinction of `--root` and `--installroot` that for instance `zypper` has is meaningful to this kind of use cases. Would be nice if there was a way to state the installation, but only the installation, should happen to an alternate root, however the config, cache and all other interactions luet has with the files system would be based on the current root.
> 

On that, I think we have https://github.com/mudler/luet/blob/946524f90de7c4c9f579749f868b91f5f58f5750/contrib/config/luet.yaml#L100 which does this distinction for config files, but not for cache and temporarly data, I'm not the author of that part of code, so I'm not sure if would apply for caches too (but doesn't look like)

> I also could not manage to actually use `luet util unpack` form a local tarball image/package.

yep, `luet util unpack` works only with container image references, it doesn't work with local tarballs

**Comment by davidcassany** [comment]
> On that, I think we have https://github.com/mudler/luet/blob/946524f90de7c4c9f579749f868b91f5f58f5750/contrib/config/luet.yaml#L100 which does this distinction for config files, but not for cache and temporarly data, I'm not the author of that part of code, so I'm not sure if would apply for caches too (but doesn't look like)

Probably it would make sense to implement a `cache_from_host` flag or extend `config_from_host` functionality to include cache, even I think it makes sense to keep it separated for bootstrapping scenarios. Our cOS use cases in general are sort of a niche use cases.

**Comment by mudler** [comment]
> `cache_from_host`



> > On that, I think we have https://github.com/mudler/luet/blob/946524f90de7c4c9f579749f868b91f5f58f5750/contrib/config/luet.yaml#L100 which does this distinction for config files, but not for cache and temporarly data, I'm not the author of that part of code, so I'm not sure if would apply for caches too (but doesn't look like)
> 
> Probably it would make sense to implement a `cache_from_host` flag or extend `config_from_host` functionality to include cache, even I think it makes sense to keep it separated for bootstrapping scenarios. Our cOS use cases in general are sort of a niche use cases.

Created https://github.com/mudler/luet/issues/208 :+1:

**Comment by davidcassany** [comment]
I did some further tests about running the above procedure but installing in different filesystems and I realized that while checking installed files from a luet package in btrfs and ext filesystem raises some glitches. No complaints on the xattrs though. Only issues for sizes under 4096 (does btrfs allow lower sized than that?) and for nlinks.
