### ISSUE TITLE
"make local-iso" fails with 'unknown command "makeiso" for "luet"'

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#148]
**cos-toolkit version:**

git checkout @ 983f36ea893bbcb84dbde6b316f82547101600b0

**CPU architecture, OS, and Version:**
Linux xps13 5.11.12-1-default #1 SMP Wed Apr 7 17:30:21 UTC 2021 (92a542e) x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**

```
> make local-iso
/usr/bin/luet create-repo --tree "/abuild/projects/rancher/cOS/cOS-toolkit/packages" \
    --output /abuild/projects/rancher/cOS/cOS-toolkit/build \
    --packages /abuild/projects/rancher/cOS/cOS-toolkit/build \
    --name "cOS" \
    --descr "cOS opensuse" \
    --urls "" \
    --tree-compression zstd \
    --tree-filename tree.tar \
    --meta-compression zstd \
    --type http
 Repository cOS: creating revision 2 and last update 1620136356...
/usr/bin/luet makeiso -- /abuild/projects/rancher/cOS/cOS-toolkit/iso/cOS.yaml --local /abuild/projects/rancher/cOS/cOS-toolkit/build
unknown command "makeiso" for "luet"
make: *** [make/Makefile.iso:26: local-iso] Error 255
```

**To Reproduce**

see above

**Expected behavior**

no error

**Logs**

**Additional context**

`makeiso` was introduced in https://github.com/rancher-sandbox/cOS-toolkit/commit/08c0c012953e367809f065dfd7c6e6560046d110

**Comment by kkaempf** [comment]
`luet install extension/makeiso` was run before

**Comment by kkaempf** [comment]
`luet version 0.14.1-g946524f90de7c4c9f579749f868b91f5f58f5750 2021-05-04 07:56:58 UTC`

**Comment by mudler** [comment]
can you check if `luet-makeiso` is in your $PATH? `luet` just checks for the corresponding extension. `luet makeiso` its equivalent to run `luet-makeiso` directly

**Comment by kkaempf** [comment]
No, it's not. `luet<TAB>` in bash results in
```
luet                  luet-geninitramfs     luet-kernel-switcher
```

**Comment by kkaempf** [comment]
Hmm, I just ran `sudo luet install extension/makeiso` again and now it's working.
