### ISSUE TITLE
unprivileged 'make local-iso' drops /usr/sbin/mkfs.ext4

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#151]
**cos-toolkit version:**
git checkout 0552a69fe515353addd6e561372635b23859deb6

**CPU architecture, OS, and Version:**

**Describe the bug**

After successfully building and booting a `local-iso`, `cos-installer` fails with
```
which: no mkfs.ext4 in (...)
```

**To Reproduce**

`make local-iso`
boot resulting ISO and run `cos-installer` as described in motd.

**Expected behavior**

`cos-installer` starts to install on given block device.

**Logs**

**Additional context**

**Comment by mudler** [comment]
@kkaempf which flavor was it? do you have the make build logs too?

**Comment by kkaempf** [comment]
I did a `make` and `make local-iso` straight from a git checkout.

Where would I find the build logs ?

**Comment by mudler** [comment]
mmh we don't do annotate logs anywhere by default at the moment, but there is an option in luet to write logfiles: https://github.com/mudler/luet/blob/master/contrib/config/luet.yaml#L6 , or we can just use `tee`..

**Comment by kkaempf** [comment]
:thinking: now `make local-iso` produces a working image, trying `make iso` next if this makes a difference.

**Comment by mudler** [comment]
> Ugs, `sudo make iso` fails with
> 
> ```
>  Error: Failed syncing repository: cOS: While downloading repository.yaml: failed listing images: parsing image name ":repository.yaml" failed: invalid reference format
> ```

looks like https://github.com/rancher-sandbox/cOS-toolkit/blob/master/make/Makefile.build#L30 is not consumed here https://github.com/rancher-sandbox/cOS-toolkit/blob/master/make/Makefile.iso#L61

**Comment by kkaempf** [comment]
:+1:
This error is actually in `master`. Fixing in #161.

**Comment by kkaempf** [comment]
Now I can't reproduce it any more. Confusing.

**Comment by kkaempf** [comment]
reopening since it just happened again:

- sudo make build
- chmod 777 build
- make local-iso
- boot resulting ISO with qemu
- run `cos-installer /dev/sda`

**Comment by kkaempf** [comment]
Here's the problem

`/sbin/mkfs.ext4` exists but is just a symlink to `/usr/sbin/mkfs.ext4`, which does **not** exist.

**Comment by kkaempf** [comment]
This doesn't happen with `make iso`, only with `make local-iso` it seems. Adapting summary.

**Comment by kkaempf** [comment]
`cos-system-0.5.3+3` created in `build/` _does_ contain `/usr/sbin/mkfs.ext4`. It seems to get deleted during `make local-iso`
