### ISSUE TITLE
Find another host for yq-utils-3.4.1.package.tar.gz

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#155]
**Is your feature request related to a problem? Please describe.**

`luet install utils/yq` times out when downloading yq-utils-3.4.1.package.tar.gz

```
 yq-utils-3.4.1.package.tar.gz -    4% [===>                                                                                                     ] (133 kB/3.1 MB, ) [15m54s:0s] Failed downloading package yq Error on download artifact: read tcp 192.168.0.25:52978->144.76.79.176:443: read: connection timed out
```

**Describe the solution you'd like**

Plain, simple, fast install of `yq`

**Describe alternatives you've considered**

Fix the current host ?

**Additional context**

**Comment by mudler** [comment]
We could have a repository hosted on gh-pages as a drop-in solution, but I wouldn't really go on that route.  If we tackle #108 we will likely not need both of them, but just have one single binary

**Comment by mudler** [comment]
This is now fixed, yq now lives in the `cOS` repositories
