### ISSUE TITLE
Update yq to v4.x

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#157]
Citing from https://mikefarah.gitbook.io/yq/

> Support for v3 will cease August 2021, until then, critical bug and security fixes will still get applied if required.

**Comment by mudler** [comment]
we do a little usage of yq (just reading package files) and to generate the specfile to refer to the remote repositories.

I don't think we will really need them in the long term, #108 should provide the required tooling glue to avoid them on the build host

**Comment by mudler** [comment]
That time of the year has arrived (August) and yq3 is not maintained anymore
