### ISSUE TITLE
'make clean' leaves /tmp/luet-geniso511891688 in place

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#158]
**cos-toolkit version:**

luet version 0.14.1-g946524f90de7c4c9f579749f868b91f5f58f5750 2021-05-04 07:56:58 UTC
git @ 680349531f07406685aaa200915f064c9d926527

**CPU architecture, OS, and Version:**

openSUSE Tumbleweed x86_64

**Describe the bug**

This is actually two bugs: a) failure of `make local-iso` and b) wasted disk space in `/tmp`.

`make local-iso` fails with

```
ERRO[0000] fatal error: stat /tmp/luet-geniso511891688/overlayfs/boot/vmlinuz: no such file or directory 
```

I can't remember how I got into this state, but would assume that a `make clean` (or do we need a `make realclean` while `make clean` keeps a 'cache'  ?!) would give me a "clean plate" to start over.

**To Reproduce**

Simplest probably is to
```
rm `find /tmp/luet-geniso* -name vmlinuz`
```

**Expected behavior**

`make clean` resets everything and a subsequent `make local-iso` succeeds.

**Logs**

**Additional context**

**Comment by mudler** [comment]
you should be able to set `TMPDIR` temporarly to force a specific temporary directory, but we should make `makeiso` cleanup in case of failure

**Comment by kkaempf** [comment]
Hmm, removing this tempdir creates another one (`/tmp/luet-geniso613094909`) but gives me the same error when running `make local-iso`

```
ERRO[0000] fatal error: stat /tmp/luet-geniso613094909/overlayfs/boot/vmlinuz: no such file or directory 
```

`make local-iso` needs another prerequiste. But which one ? :thinking:

**Comment by kkaempf** [comment]
`make build` puts `vmlinuz` back in place

**Comment by mudler** [comment]
@kkaempf Is this still happening?

**Comment by kkaempf** [comment]
well, it apparently is another privileged vs. unprivileged case and happens if you run "make build" (resp. "make clean") as non-root.

Docs have been adapted meanwhile. Closing.
