### ISSUE TITLE
After install, cos-toolkit issue file is displayed on derivatives

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#163]
**cos-toolkit version:**
https://github.com/rancher-sandbox/cOS-toolkit/commit/680349531f07406685aaa200915f064c9d926527

**CPU architecture, OS, and Version:**
Not relevant

**Describe the bug**
https://github.com/rancher-sandbox/cOS-toolkit/blob/680349531f07406685aaa200915f064c9d926527/packages/installer/installer.sh#L215 writes to the persistent storage, so if a derivative gets installed, after boot will get displayed the default password of cos and the content of the /etc/issue of cos-toolkit

**To Reproduce**
Install a derivative, e.g. https://github.com/rancher-sandbox/epinio-appliance-demo-sample

**Expected behavior**
To not see the cos-toolkit message 

## Action Items
- [ ] Drop the hardcoded post-installation cloud-init file installation
- [ ] Have a mechanism in place similar to what we do for `COS_INSTALL_CONFIG_URL`  that copies a custom cloud-config file also to  `/usr/local/cloud-config`. We can then have a default that can be opt-out but mimics the same behavior we have currently

**Comment by Itxaka** [comment]
@mudler First part is ok, to drop that but dont we have a system in place already for this for the second part?? like you overwrite branding for example as it currently stands and you get this in place?

**Comment by Itxaka** [comment]
Like Im not sure it even needs to be part of the installer...we use oem for all this, including the branding so thats the place for this stuff??

**Comment by mudler** [comment]
we have `/usr/local/cloud-config` which act like the "user" version for cloud config files already. The files dropped in there are executed during boot as well, like "/oem", and they are part of `COS_PERSISTENT` - it's a way to override furthermore what's in `/oem`. The installer was dropping a file there to give some heads-up post install that can be easily removed by the user

**Comment by mudler** [comment]
So to speak, it should be about dropping the hardcoded drop-in for something customizable, like https://github.com/rancher-sandbox/cOS-toolkit/blob/680349531f07406685aaa200915f064c9d926527/packages/installer/installer.sh#L209

**Comment by Itxaka** [comment]
but they can(and will) override the branding anyway with something like this: https://github.com/rancher-sandbox/epinio-appliance-demo-sample/blob/master/packages/epinioOS/03_branding.yaml

So dropping it from the installer should be good enough, not sure why would we need to also provide it during the install? Im just not seeing a use case for that tbh

**Comment by mudler** [comment]
> but they can(and will) override the branding anyway with something like this: https://github.com/rancher-sandbox/epinio-appliance-demo-sample/blob/master/packages/epinioOS/03_branding.yaml

That's true only for who is creating a derivative, not for who is installing it. The installer accepts currently a custom cloud-config file, but that's placed under `/oem`. The point here is augmenting it to have another parameter which operates over `/usr/local/cloud-config` instead

**Comment by Itxaka** [comment]
@mudler maybe Im not understanding correctly. Arent the installers supposed to use user-data to configure their instances? Why would anyone use a manual method to provide a file uploaded somewhere that can (and should) be done by the user-data methods used by...everyone when deploying? You can also use user-data on qemu for example and on baremetals you should be able to use user-data as well with a config-drive.

I still dont see the use case for this when we have user-data and deployers are probably using it everywhere? Can you provide a use case for deploying file during the install that end up in `/usr/local/cloud/config` ?

**Comment by Itxaka** [comment]
I mean, I can just expand the `$COS_INSTALL_CONFIG_URL` to also save the data to the cloud config dir but what is the point there?
