### ISSUE TITLE
Spike: build ARM/arm64 images with GRUB

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#19]
This card is a spike on how to build images for ARM, but most importantly to find out if we can re-use our GRUB+dracut approach currently used in amd64-land in ARM devices. (maybe chainloading?)

Create issues as necessary as we find more informations and we find a way to achieve ARM images.

## Additional context

- For building ARM images, have a look at https://github.com/Luet-lab/luet-embedded/blob/master/scripts/arm_image.sh  for inspiration, we might want an extension for it, similarly on how we build ISOs
- https://media.ccc.de/v/946-uefi-grub2-on-raspberry-pi
- https://forum.odroid.com/viewtopic.php?t=26894
- https://www.hellion.org.uk/blog/posts/grub-on-uboot-on-qemu/
- https://packages.debian.org/jessie/grub-uboot
- http://rglinuxtech.com/?p=2595
- https://github.com/pftf/RPi4

**Comment by dragonchaser** [comment]
Updated epic #496
