### ISSUE TITLE
Split recovery image and system image into separate artifacts

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#192]
Currently we are using the same image for the recovery partition than for the active (`COS_ACTIVE`) loop device. For a plain system like the one we are using now it might be reasonable, however for a derivative service specific appliance this approach does not have much sense.

I'd say that generically speaking having production services into the recovery partition is a bad idea (even a dangerous idea) and we should facilitate having some control about what is the recovery system and what is the production system. 

For that I would simply create different images, `system/cos` and `recovery/cos`. `system/cos` used for the `COS_ACTIVE` and `COS_PASSIVE ` loop devices and the  `recovery/cos` one used for the COS_SYSTEM partition. Also the immutability approach could be expressed with different defaults for the recovery system than for the COS_ACTIVE system.

In addition to that and linked with #217 I believe having a recovery image contained in a squashfs filesystem is better for few reasons:

* Immutability as it was well known live image, no persistence at all and whole system gets overlayed.
* No need of applying any sort of custom layout code at boot (just use the well established and robust live boot procedure)
* Compressed images so less space in disk, I'd say the performance penalty for a recovery system is just fine.
* It can be populated without having to mount any filesystem (relevant for containerized builds)

## Action items

- [x] Split `system/cos` into `recovery/cos` and `system/cos`, so that during upgrades it can be specified a different image to upgrade recovery from
- [x] ~~Make the recovery script accept an image to use to recovery from, besides the current behavior which is replicating the recovery to the ACTIVE and PASSIVE~~ / Make sure `cos-upgrade` works from the recovery
- [x] Move the recovery layout to squashfs instead of an image
- [ ] Fix/Add new tests

**Comment by mudler** [comment]
The move to squashfs is more complex than it looks like: at the moment we are relabeling image files and copying them over instead of recreating them, and more over we should ship a squashfs within the final image, containing another image which is squash'fsed.

**Comment by mudler** [comment]
WIP branch at https://github.com/rancher-sandbox/cOS-toolkit/tree/split_recovery
