### ISSUE TITLE
Verify images also when upgrading to specific container images

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#223]
**Is your feature request related to a problem? Please describe.**
After #95  is delivered and #185 merged we have to find a way to ensure the same mechanism works when specifying single images

**Describe the solution you'd like**
When specifying single images, pull also the metadata file and run the mtree plugin manually

**Describe alternatives you've considered**
N/A

**Additional context**
Blocked by https://github.com/rancher-sandbox/cOS-toolkit/pull/185 , Follow up of #95

## Requirements

 - [x] upgrade script checks for mtree checksums on single image upgrade https://github.com/rancher-sandbox/cOS-toolkit/pull/234
 - [x] default upgrade by channel works as before

**Comment by mudler** [comment]
I'm marking this as part of MVP - this is because we can upgrade also by specifying single tags, and image verification should work for upgrades in general

**Comment by Itxaka** [comment]
Merged! Now all upgrade types will check for mtree signatures and fail if they do not match
