### ISSUE TITLE
Update developer workflow

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#258]
As #255 has shown, the developer workflow (and esp. its make targets and tools options) is not well documented.

**Comment by mudler** [comment]
We had docs about the make targets : https://github.com/rancher-sandbox/cOS-toolkit/blob/master/docs/dev.md#run-tests although I am pretty sure it is out-of-sync by now

**Comment by kkaempf** [comment]
Then let's bring it up-to-date

**Comment by kkaempf** [comment]
WIP PR: https://github.com/rancher-sandbox/cOS-toolkit/pull/290

**Comment by kkaempf** [comment]
run-qemu improvements: #326

**Comment by mudler** [comment]
Closing the issue, both PR were merged and card was moved to done
