### ISSUE TITLE
ci: test failures with timeout

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#277]
**cos-toolkit version:**
Not relevant

**CPU architecture, OS, and Version:**

**Describe the bug**
Occasionally tests seems to fail reconnecting.

**To Reproduce**
N/A

**Expected behavior**
Tests to pass

**Logs**
```
• Failure [363.635 seconds]
cOS Upgrade tests - Images unsigned
/Users/runner/work/cOS-toolkit/cOS-toolkit/tests/upgrades-images-unsigned/upgrade_test.go:10
  After install
  /Users/runner/work/cOS-toolkit/cOS-toolkit/tests/upgrades-images-unsigned/upgrade_test.go:21
    when images are not signed
    /Users/runner/work/cOS-toolkit/cOS-toolkit/tests/upgrades-images-unsigned/upgrade_test.go:22
      upgrades to latest available (master) with --no-verify and reset [It]
      /Users/runner/work/cOS-toolkit/cOS-toolkit/tests/upgrades-images-unsigned/upgrade_test.go:23

      Timed out after 205.760s.
      Unexpected error:
          <*errors.errorString | 0xc00005bf50>: {
              s: "ssh: handshake failed: read tcp 127.0.0.1:49407->127.0.0.1:2222: i/o timeout",
          }
          ssh: handshake failed: read tcp 127.0.0.1:49407->127.0.0.1:2222: i/o timeout
      occurred

      /Users/runner/work/cOS-toolkit/cOS-toolkit/tests/sut/sut.go:154
------------------------------
```

**Additional context**
This usually can be caused by either two things: or we timeout too fast, or either the login user/pass is not working.
We had seen this kinda of issues in the past where the cloud-init failed to apply the user settings in the early stages due to service boot order not properly in place.

It did happened also to me locally, when I've tried to reproduce it (after quite some attempts) that I could not login as well, as user/pass didn't matched. A reboot fixed it, so this suggests there is something which is failing occasionally that we should look at.

https://github.com/rancher-sandbox/cOS-toolkit/pull/260/checks?check_run_id=2827527337

**Comment by mudler** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/runs/2902939394?check_suite_focus=true

**Comment by mudler** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/runs/2927158997?check_suite_focus=true

**Comment by mudler** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/runs/2952882426?check_suite_focus=true
https://github.com/rancher-sandbox/cOS-toolkit/runs/2952924812?check_suite_focus=true

**Comment by mudler** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/runs/2956883525?check_suite_focus=true

**Comment by davidcassany** [comment]
Something to keep in mind is that some of these tests run a downgrade to some old images, so some failures might happen on booting old images... this is tricky to trace and asses if this still happening in up to date images. Probably we can try to think of some other upgrade strategy in tests, like discovering the latest released image and upgrade to that image for the `--docker-image` upgrade use case. All to avoid going back in time.

Also I have been thinking that we should have some sort of failure mechanism to lead the system to fallback in those cases. I am thinking to something like forcing the system to fail unless there is root password defined or some authorized ssh key. This could be done with some unit service that has condition on the existence (or not) of some file, so if the user config is not there leads the system to a reboot. What I do not see clear is how to trigger the fallback mechanism in such a case.

**Comment by davidcassany** [comment]
> What I do not see clear is how to trigger the fallback mechanism in such a case.

Probably we could think of using some sort sentinel file in COS_STATE, COS_RECOVERY or COS_OEM, to track some systemd boot failure and the actual system that failed so grub can default to something else on reboot.

Probably COS_OEM is not a bad choice, I have also been thinking that probably we should give it a differentiated treatment (currently it is optional as COS_PERSISTENT and defined in `/run/cos/cos-layout.env`. Probably we could _force/assume_ the existence of COS_OEM in any case (so no need to define it in cos-layout.env) and assume it has a role in the boot and cloud-init config procedures.

Anyway this sort of issues we are seeing in the CI in the form of timeouts are also revealing we need some recovery / fallback for those cases. To me it looks liked we reached the situation of having to define some sanity boot checks, we knew we'd fall at some point into this burden... :sweat_smile:

**Comment by mudler** [comment]
Another point is, we should also collect all the logs from `cos-setup` calls somewhere we can inspect later on too

**Comment by mudler** [comment]
This is happening now everytime on master, see https://github.com/rancher-sandbox/cOS-toolkit/runs/2972359148, raising prio and moving it in Todo

**Comment by mudler** [comment]
I think we can close this for now and re-open it if necessary, everything seems so much better now :+1:
