### ISSUE TITLE
Create a bootloader package that is part of `cos-recovery` and/or `cos-system` image

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#279]
Current `system/cos` or `recovery/cos` they include grub2 bootloader. This card is about of splitting grub2 related artifacts into a separate package (currently part of the base package) so it can be easily consumed as part of image building procedures (ISOs and disks).

This will facilitate keeping all image related artifacts consistently aligned in `manifest.yaml`.

**Comment by mudler** [comment]
@davidcassany isn't this already done? we have https://github.com/rancher-sandbox/cOS-toolkit/tree/master/packages/grub-config already split, or I'm missing something?

**Comment by davidcassany** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/tree/master/packages/grub-config is only about the configuration. I am thinking about the bootloader binaries here. Something like `live/boot` but all based on distro packages which could be used for both disks and isos.
