### ISSUE TITLE
"live/init" does not exist

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#280]
**cos-toolkit version:**

**CPU architecture, OS, and Version:**

**Describe the bug**

https://github.com/rancher-sandbox/cOS-toolkit/blob/master/docs/dev.md#testing-iso-changes reads
> **Testing ISO changes**
> 
> To test changes against a specific set of packages, you can for example:
```
$> make PACKAGES="live/init"  build local-iso
```

However, running this fails with
> Error: Candidate not found: No versions found for: live/init->=0

**To Reproduce**

Run `make PACKAGES="live/init"  build local-iso`

**Expected behavior**

Command to succeed

**Logs**

**Additional context**

**Comment by mudler** [comment]
It doesn't exist indeed anymore, docs should be updated to provide __another__ package to build as an example indeed.
