### ISSUE TITLE
Running default ISO with "make run-qemu" has insufficient disk space

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#281]
**cos-toolkit version:**

v0.5.3+1 (git HEAD as of 2021-Jun-15)

**CPU architecture, OS, and Version:**

x86_64 on openSUSE Tumbleweed

**Describe the bug**

Running
```
sudo make iso
QEMU=qemu-system-x86_64 make run-qemu
```
succeeds in booting but a subsequent `cos-install` fails with
> Error: The location 23100MB is outside of the device /dev/sda.

because `/dev/sda` is too small

**To Reproduce**

```
cos:~ # cat /proc/partitions 
major minor  #blocks  name

   7        0     318656 loop0
   2        0          4 fd0
   8        0   16777216 sda
  11        0     736256 sr0
cos:~ # cos-installer sda
You should use an available device. Device sda does not exist.
cos:~ # cos-installer /dev/sda
Formatting drives..
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.152893 s, 6.9 MB/s
Error: The location 23100MB is outside of the device /dev/sda.
cos:~ # cat /proc/partitions 
major minor  #blocks  name

   7        0     318656 loop0
   2        0          4 fd0
   8        0   16777216 sda
   8        1      48128 sda1
   8        2      48128 sda2
   8        3   14648814 sda3
  11        0     736256 sr0
```

**Expected behavior**

`/dev/sda` is sufficiently large to make `cos-installer` succeed.

**Logs**

see above

**Additional context**

**Comment by mudler** [comment]
Right, the packer qemu templates should be updated to bump the default disk size to at least fit the requirements of the installer

**Comment by mudler** [comment]
Ah, nothing to do actually with packer. It's about bumping the default created drive here: https://github.com/rancher-sandbox/cOS-toolkit/blob/master/make/Makefile.run#L20
