### ISSUE TITLE
master branch CI builds are taking an insane amount of time

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#294]
Builds in `master` branch are taking an insane about of time to build. Current opensuse flavor in master takes more than 2h for a full tree build and more than 3h for a fedora and ubuntu. After that then ISO and images builds and later on functional tests start. So the whole process is several hours long, more over, during this time, the job can be cancelled if there are further pushes to master.

Apparently this seams to be caused by having to rebuild all the packages from the cache, so we unpack and repack many times. By looking the logs it even looks like we are doing it several times in a row for the same packages.

**Comment by mudler** [comment]
🤔 we can also use dynamic matrix generation and have a separate job for each package, e.g. https://github.com/mocaccinoOS/mocaccino-micro/blob/99ac3b956e36e337dd588e02b403e7452818fb85/.github/disabled/build.yml#L27 . It definitely worth a try to see if improve overall build time

**Comment by mudler** [comment]
I guess we can close this for now. Build times reduced significantly, and in case no changes are made, no packages are built at all from the CI
