### ISSUE TITLE
'raw' fails in CI with "cp: cannot stat 'recovery/usr/share/grub2/x86_64-efi/*.mod': No such file or directory"

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#296]
**cos-toolkit version:**

master branch at e411d8b3f0044edffc6fafa39f3097b471ef46bc
**CPU architecture, OS, and Version:**

CI run: https://github.com/rancher-sandbox/cOS-toolkit/runs/2856393413?check_suite_focus=true

**Describe the bug**

'raw-img' fails with

```
Run # Apparently having other repositories enabled causes luet to hang
removed '/etc/luet/repos.conf.d/luet.yml'
removed '/etc/luet/repos.conf.d/mocaccino-extra-stable.yml'
removed '/etc/luet/repos.conf.d/mocaccino-repository-index.yml'
/__w/cOS-toolkit/cOS-toolkit/images/img-builder.sh
 Downloading file repository.yaml from build


⠈  Downloading file tree.tar.zst from build
 Downloading file repository.meta.yaml.tar.zst from build
 🏠  Repository cOS revision: 1 - 2021-06-18 07:49:05 +0000 UTC
 ℹ Repository: cOS Priority: 0 Type: disk
WWW
 No packages to install
cp: cannot stat 'recovery/usr/share/grub2/x86_64-efi/*.mod': No such file or directory
make: *** [make/Makefile.raw:55: raw_disk] Error 1
Error: Process completed with exit code 2.
```

**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

**Comment by davidcassany** [comment]
I can't explain why it did fail at this point. Looks like the results from the previous build were not properly downloaded, however there are no complaints from GHA.

```
cp: cannot stat 'recovery/usr/share/grub2/x86_64-efi/*.mod': No such file or directory
```
these files are part of the installed package and for some reason luet did not install anything, see the luet output just before:

```
...
No packages to install
cp: cannot stat 'recovery/usr/share/grub2/x86_64-efi/*.mod': No such file or directory
```

**Comment by mudler** [comment]
There is a difference running master and PR jobs, PR jobs are not generating all packages, while on branches we do : https://github.com/rancher-sandbox/cOS-toolkit/blob/0f74148aef837a86431be97900f90a4e6b262ca5/.github/workflows/build.yaml#L92 that's in order to speed up things, master needs to have all the packages published in order to have them available on install 

The flag which enables that behavior is `--only-taget-package`

**Comment by davidcassany** [comment]
And how target packages are determined? By the diff from master? If so that could explain the failure because master was not published since master builds are mostly stalled in performance issues.

**Comment by mudler** [comment]
> And how target packages are determined? By the diff from master? 

It is infered from the manifest file, see https://github.com/rancher-sandbox/cOS-toolkit/blob/0f74148aef837a86431be97900f90a4e6b262ca5/make/Makefile.build#L42

> If so that could explain the failure because master was not published since master builds are mostly stalled in performance issues, indeed there was workflow running for about 3h that got cancelled once #292 got merged to start a new workflow from the new master... 😞

yuck.. 😞

**Comment by davidcassany** [comment]
5h later and the workflow triggered by https://github.com/rancher-sandbox/cOS-toolkit/pull/292 finished and packages are finally published. I guess this should have fixed this issue.

**Comment by mudler** [comment]
For local builds, we always need to be sure we build recovery/cos individually as it is consumed by the script. We will have to figure out a better way to speedup the CI build times, but that's another issue
