### ISSUE TITLE
Simplify makefile

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#32]
Besides some general refactoring which is needed, we should have one command that :

- generates all packages (e.g. already present `make rebuild-all`)
- the ISO (e.g. already present `make local-iso`)
- Finally a target to run qemu with it (to write `make run-qemu`)

Consider also adapting current GHA pipelines to test the new process too (without `run-qemu`, if that's hard to test)

**Comment by kkaempf** [comment]
This should also merge `.envrc` into `Makefile`

**Comment by mudler** [comment]
All the items on the issue were covered, closing it
