### ISSUE TITLE
Build Azure images with Packer

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#341]
This card is about having a packer template for Azure by using an image created by #235 

**Additional context**
Part of #208 

## Requirements

 - [x] packer templates for azure -> https://github.com/rancher-sandbox/cOS-toolkit/pull/412
 - [x] docs explaining how the process works, from creating the raw image to getting the final image -> https://github.com/rancher-sandbox/cos-toolkit-docs/pull/7
 - [x] upstream issue/pr for packer (userdata not available)  https://github.com/hashicorp/packer-plugin-azure/issues/121
 - [x] #474
 - [x] new version released of packer-plugin-azure with the user_data patch, or mention in the docs the requirement

**Comment by Itxaka** [comment]
Api keys obtained.

We cannot currently build azure images because we are missing the user-data input from linuxkit as its stuck upstream in limbo https://github.com/linuxkit/linuxkit/pull/3585

Currently booting manually works, executing the user-data manually also seems to work, so once we fix that metadata issue, we should be able to automate the packer templates.

I will send a draft PR

Note: We may have issues with the custom_data VS user_data. Packer currently supports custom_data ONLY. So we may need to send a patch upstream to support user_data as well in the packer builder if we cannot use the custom_data properly.

**Comment by Itxaka** [comment]
Draft PR: https://github.com/rancher-sandbox/cOS-toolkit/pull/412

**Comment by Itxaka** [comment]
Blocked due to user-data: https://github.com/rancher-sandbox/cOS-toolkit/issues/355

**Comment by Itxaka** [comment]
Thanks to @davidcassany yip has now support for the azure metadata. Tested and the metadata ends up in the proper place.

Unfortunately packer does not support user data only custom data which is passed during provisioning and requires cloud-init or waagent to process....¬_¬

Seems like an issue  + PR is required to the https://github.com/hashicorp/packer-plugin-azure repo to support using user-data :weary:

**Comment by Itxaka** [comment]
yikes, seems like upstream azure-sdk did not support userdata until....01/03/2021 -> https://github.com/Azure/azure-sdk-for-go/blob/main/services/compute/mgmt/2021-03-01/compute/models.go

The api packer is using is currently....2018-04-01

Like its gonna be a hard sell to send an update upstream for this...

**Comment by Itxaka** [comment]
Looks like its easy to implement actually :O will send a patch upstream to support user_data and see what they think about

**Comment by Itxaka** [comment]
opened https://github.com/hashicorp/packer-plugin-azure/pull/122 and sent https://github.com/hashicorp/packer-plugin-azure/issues/121

tested locally with that patch and it works as expected :o

**Comment by Itxaka** [comment]
Templates are ready and pushed. They work, I have build and image based of the vanilla image. Unfortunately I dont think images are shareable so derivatives will need to upload their own vanilla image and then build from there. We could also make the bucket where we store the images publicy accessible so they can create recovery images from there but I dunno, something to discuss.

There is this shared image gallery but I have no idea how that works anyway :D

https://github.com/rancher-sandbox/cOS-toolkit/pull/412 missing the docs

**Comment by mudler** [comment]
I've pinged upstream maintainers here https://github.com/hashicorp/packer-plugin-azure/pull/123#issuecomment-886509266. let's see what happens

**Comment by mudler** [comment]
Follow up opened https://github.com/hashicorp/packer-plugin-azure/pull/131

**Comment by mudler** [comment]
Azure docs seems quite confusing in this regard, here I read that Images in the shared gallery should be generalized first: https://docs.microsoft.com/en-us/azure/virtual-machines/shared-image-galleries#generalized-and-specialized-images which seems to involve `waagent`. But here instead https://docs.microsoft.com/en-us/azure/virtual-machines/generalize seems generalization is not required, if it's not required, should be just a matter of running 
```
az vm generalize \
   --resource-group myResourceGroup \
   --name myVM
```

**Comment by mudler** [comment]
Opened https://github.com/rancher-sandbox/cOS-toolkit/issues/341 to dig into the shared image gallery as a separate story
