### ISSUE TITLE
Fedora/Ubuntu 0.5.7 mtree check failed on deployment

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/cOS-toolkit#351]
Using the latest published version (0.5.7) of both ubuntu and fedora with cos-deploy, mtree checks fail. I have not be able to capture the logs due this being discovered while building AMIs with packer, which means that the instance were immediately terminated.

Need to investigate further

**Comment by Itxaka** [comment]
looks like its due to xattrs.

`"usr/bin/arping": keyword "xattr.security.capability": expected AQAAAgAgAAAAAAAAAAAAAAAAAAA=; got `

**Comment by Itxaka** [comment]
weird, looks like in the ubuntu image only arping has xattrs and on extraction we can't check them becuase we are on a recovery system so probably we dont have xttras?


```
$ yq r /tmp/ubu2/cos-system-0.5.7.metadata.yaml mtree|grep xattr 
#      keywords: type,xattrs,sha512digest
    xattr.conf sha512digest=8e4dec1aa4f3e60a50082fcc50150710175c89fe7628e1df51cc0f758b87694d7e09b7dc6ce301be8514047904ce1073362f223c001c74a18a0f6e7060d6746b
    arping xattr.security.capability=AQAAAgAgAAAAAAAAAAAAAAAAAAA= sha512digest=5699a0c3a684a4e177e20270be421f88c0cded21c13a02767e9311a6bbcc32980ce015e072bc198bbe4fecae416148866b8b4b1fe081c7bfd4e2e88b4a4407f6

```

**Comment by Itxaka** [comment]
either the xattrs are lost on the tar of the image (something to check on luet side) or the filesystem where we extract the temp image needs to be mounted with `user_xattr`

**Comment by Itxaka** [comment]
blergh, I have no idea how to enable xattrs on btrfs (my current filesystem) so I cannot test this properly, but Im pretty sure its a side issue of building on ubuntu (which probably has xattrs active) and then either the tar process is not storing the xattrs or the target filesystem not having xattrs enabled

**Comment by mudler** [comment]
Are you specifying an image or using channel upgrades? It might be due to how we decompress the image, or even the rsync call skipping extra attributes

**Comment by Itxaka** [comment]
@mudler image only. Im suspecting that because we mount fs during cos-depoy and we do not pass the xattrs attribute it migth ignore it. In some cases we dont even pass the defaults to mount the fs, so we migth be losing the xattrs stuff in there. Currently testing it...

**Comment by Itxaka** [comment]
on rsync we use the -X so that means it should preserve the attributes, which point to either the tar or the fs...

**Comment by Itxaka** [comment]
Creating an ubuntu iso with the package xattr added and booting from it.

  - Booting from active.img
    - arping has the correct xattrs
  - Booting from recovery and runnin cos-deploy
    - Fails to validate mtree, arping xattrs failed
    - This is expected in each image, recovery should be the same in all images
  - Booting from active.img  and installing from docker-image directly instead of the iso:
    - arping has NO xattr
  - Booting from active.img and using luet to unpack the image, check perms
    - arping has NO xattr
 

From this tests seem clear that when packing the ubuntu cos-system, arping has the xattributes intact (as shown by the mtree file and the iso) but when installing from docker image it just doesnt.

So either we are messing it up when tranforming it into a docker image (which is what ends up in the quay repos) or we are messing on decompression from luet.

**Comment by mudler** [comment]
I'm a bit unsure that's caused by luet, because we have test suite there to check special bits - the thing is we do tests only against tarballs, and not with uploaded images. I'm bit concerned that can be happening on the registry side of things. Did you try to docker run the image directly and check there?

**Comment by Itxaka** [comment]
looks like the problem is in upstream docker[0] as the COPY command does not preserve xattrs and when generating the docker images we extract the artifact and generate a Dockerfile that only does the COPY command[1]

Supposedly buildkit supports xattrs....

[0] https://github.com/moby/moby/issues/35699
[1] https://github.com/mudler/luet/blob/654b5b48cd1a270f0f4e8ea49b726ab2647bd37f/pkg/compiler/types/artifact/artifact.go#L157

**Comment by Itxaka** [comment]
Indeed the packages and the iso contain the arping with intact xattrs.

Using DOCKER_BUILDKIT=1 to push packages didnt seem to work for me, the files inside have lost their xattrs BUT I noticed that when untarring manually, you **need** to pass the following flags to extract the files with the proper attrs `--xattrs --xattrs-include='*'`

just something to have in mind when testing this. Also something to look at in the source for buildkit to see how its storing the xattr

**Comment by Itxaka** [comment]
I also tried to substitute the docker build command with the (buildx plugin)[https://github.com/docker/buildx/] to hijack the luet calls and force it to use buildkit capabilities but its not working. Im guessing becuase Im doing the build process on a system that does not support those attrs? 

I'll try bulding on a ubuntu image directly like in the CI build

**Comment by Itxaka** [comment]
indeed something has to be wrong there, becuase If I set other values they are in there no problem:


```
NAME: usr/bin/arping
PAX: map[SCHILY.xattr.security.capability:  atime:1625816934.20455111 ctime:1625816934.20455111]
```

**Comment by Itxaka** [comment]
So it has something in the value for sure:

```
itxaka@itxaka-VirtualBox:~/cOS-toolkit/test$ getcap usr/bin/arping 
usr/bin/arping = cap_net_raw+ep
```
```
itxaka@itxaka-VirtualBox:~/cOS-toolkit/test$ getfattr -m "-" -d usr/bin/arping 
# file: usr/bin/arping
security.capability=0sAQAAAgAgAAAAAAAAAAAAAAAAAAA=
```

Now, Im not sure why its not picking it up, maybe its not reading it as expected :/

**Comment by Itxaka** [comment]
more info, seems like underlying the 300 layers of complexity is just using this lib to copy: https://github.com/tonistiigi/fsutil/

Unfortunately, even when that lib properly tries to copy the xattrs[0] byt the time teh file arrives there it has no attrs at all:

```
FILE: arping
ATTRS FOR FILE arping: []
```

Compared with a test file that I got in there which maintains all attrs:
```
FILE: test
ATTRS FOR FILE test: [security.capabilities security.capabilit trusted.security.capability user.security.capability trusted.capability]
```

Notice that the attr `security.capability` seems to be a protected one and I been unable to set it properly. Using `setfattr` results into the key either having the `user` prefix or if using root privs `trusted` ¬_¬





[0] https://github.com/tonistiigi/fsutil/blob/8599091d69851a37058eec95da25c794ac060a0a/copy/copy.go#L278

**Comment by Itxaka** [comment]
indeed, you need to use `setcap` to set that attr:

```
# itxaka @ zeus in ~/projects/cOS-toolkit/test on git:351 x [15:06:40] C:1
$ sudo setcap cap_net_raw+ep test 

# itxaka @ zeus in ~/projects/cOS-toolkit/test on git:351 x [15:06:47] 
$ sudo getcap test                  
test = cap_net_raw+ep
```

**Comment by Itxaka** [comment]
After setting the `security.capability` attr, its clear that something is dropping it:


```
FILE: test
ATTRS FOR FILE test: [security.capabilities security.capabilit trusted.security.capability user.security.capability trusted.capability]
```

**Comment by Itxaka** [comment]
Definitevely its an issue with upstream docker build that doesnt keep the caps on COPY or ADD. Simplest fix is to drop for them moment the xattr values from the mtree checking and call it a day.

We should be able also to create an issue upstream (in buildkit probably) to follow this up.

**Comment by Itxaka** [comment]
@dragonchaser @mudler @davidcassany thoughts?

**Comment by davidcassany** [comment]
> Simplest fix is to drop for them moment the xattr values from the mtree checking and call it a day.
> 
> We should be able also to create an issue upstream (in buildkit probably) to follow this up.

I makes complete sense to me. Dropping xattrs from the mtree is bad as it weakens the verification concept, however we do not have a hard need for strict mtree checks and validations now.

**Comment by Itxaka** [comment]
PR https://github.com/rancher-sandbox/luet-mtree/pull/7 should fix this for the moment.

**Comment by Itxaka** [comment]
Opened https://github.com/moby/buildkit/issues/2250 upstream, I dont have any hope that this is fixed as probably the response we are getting is "just set caps afterwards on run" but whatever.

Closing this.
