### ISSUE TITLE
Cloud init data source: Azure

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#355]
**Is your feature request related to a problem? Please describe.**
Our cloud-init support does not include data source from Azure. We are running a fork of linuxkit to have the data sources exposed separately, although we miss the Azure cloud-init support.

**Describe the solution you'd like**
Support for Azure in the cloud-init data sources

**Describe alternatives you've considered**

**Additional context**
See also https://github.com/linuxkit/linuxkit/pull/3585 for an exampl

**Comment by mudler** [comment]
See: https://github.com/mudler/yip/pull/16 and https://github.com/davidcassany/linuxkit/pull/2

**Comment by davidcassany** [comment]
Fixed by https://github.com/mudler/yip/pull/16
