### ISSUE TITLE
Use publish outputs to publish AMI images

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/cOS-toolkit#376]
**Describe the bug**

Currently we *try* to publish the AMI image on master no matter what the changes were. First, if we dont bump the image it will fail as it uses COS_VERSION-TIMESTAMP(DDMMYYYY) for the name and we are not overwriting the image, so the step fails.
Second if we were to overwrite the image, it will cause an unnecessary cost to keep uploading the same image over and over with every bump and having leftovers in there.

**To Reproduce**
Trigger a master build in github

**Expected behavior**

Image is only updated if any packages were also updated during the publish phase

**Logs**

**Additional context**

**Comment by Itxaka** [comment]
we could probably get away with something like:

```
      - name: Publish to DockerHub 🚀
        id: publish
        run: |
          sudo -E make publish-repo 2>&1 | tee test.log
          result_code=${PIPESTATUS[0]}
          echo "::set-output name=publish::$(cat test.log)"
          exit $result_code  # This is the original status code from the command
```

And then check on the publish ami with

```
echo ${{needs.publish-opensuse.outputs.publish}}
```

Not sure what should we look for there....maybe if cos-system has been pushed or skipped? Currently testing it.

**Comment by mudler** [comment]
Superseded by #459
