### ISSUE TITLE
Trigger upgrades with Fleet on Baremetal

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#381]
**Describe the solution you'd like**
Let's see if the steps on #339 works on baremetal environment and document the required changes to make it work

**Describe alternatives you've considered**

**Additional context**
Follow up of #339 

Timebox: 2 days

**Comment by mudler** [comment]
Waiting for a baremetal host to test - meanwhile feedback is welcom also on spare HW to test on

**Comment by mudler** [comment]
I've managed to run https://github.com/rancher-sandbox/cos-fleet-upgrades-sample on a baremetal and seems to work flawlessly. I'm preparing a video of it but the steps are the same. The only sensible change is during installation, where I've run:

```
cos-installer --config https://raw.githubusercontent.com/rancher-sandbox/cos-fleet-upgrades-sample/main/fleet-cloud-init.yaml /dev/sda
```

To install automatically the cloud-init configuration. To note, the setup is still single-cluster, but shouldn't matter from a `cOS` point of view. The `Plan` of the system-upgrade-controller can be tweaked for the desired behavior.

**Comment by kkaempf** [comment]
How do you accomplish the initial boot of the machine ? PXE ?

**Comment by mudler** [comment]
Just booting with the ISO

**Comment by mudler** [comment]
Everything seems fine, I've created a video of the demo with a small summary to underline the key points in the process. It's just a matter of waiting for feedback, I'll create them as necessary.

**Comment by kkaempf** [comment]
> Just booting with the ISO

Ah, remote ISO with iLO. Just saw the video :wink:
