### ISSUE TITLE
Handle persistency layer in immutable rootfs dracut module

### ISSUE THREAD

**Issue by davidcassany** [rancher-sandbox/cOS-toolkit#430]
**Is your feature request related to a problem? Please describe.**

Configs like the following are likely to be required in most of use cases and it is curmbersome, error prone and likely to break the upgrades/downgrades (fallback).

```yaml
   initramfs:
     - if: '[ ! -f "/run/cos/recovery_mode" ]'
       name: "Persist"
       commands:
       - |
            target=/usr/local/.cos-state

            # Always want the latest update of systemd conf from the image
            # TODO: This might break the fallback system
            mkdir -p "${target}/etc/systemd/"
            rsync -av /etc/systemd/ "${target}/etc/systemd/"

            # Only populate ssh conf once
            if [ ! -e "${target}/etc/ssh" ]; then
              mkdir -p "${target}/etc/ssh/"
              rsync -av /etc/ssh/ "${target}/etc/ssh/"
            fi

            # undo /home /opt /root mount from cos immutable-rootfs module
            # TODO: we could think of configuring custom overlay paths in
            # immutable rootfs package. So this part could be omitted
            for i in home opt root; do
              sed -i "/overlay \/${i} /d" /etc/fstab
              nsenter -m -t 1 -- umount "/sysroot/${i}"
            done

            # setup directories as persistent
            # TODO: would it make sense defining persistent state overlayfs mounts
            # as part of the immutable rootfs config?
            for i in root opt home var/lib/rancher var/lib/kubelet etc/systemd etc/rancher etc/ssh; do
              mkdir -p "${target}/${i}" "/${i}"
              echo "${target}/${i} /${i} none defaults,bind 0 0" >> /etc/fstab
              nsenter -m -t 1 -- mount -o defaults,bind "/sysroot${target}/${i}" "/sysroot/${i}"
            done
```

**Describe the solution you'd like**

Immutable rootfs dracut module is capable to configure some persistent state layer, so the whole logic above could be converted into some simple config file applied at `rootfs` stage. By default the module should not do anything like that, only on demand, so the current behavior stays and the chance to cook your own soup regarding the persistent layer is still there.

Also we could allow the possibility to distinguish between fallback and active systems state if desired to prevent upgrade incompatibilities.

**Comment by mudler** [comment]
It would be also a nice idea to connect this with `cos-features`, so it can be also enabled/disabled easily from the CLI

**Comment by mudler** [comment]
The more I think to it and the more I'm convinced it should be a separate script (called by dracut modules, of course). I say this becauses in cases like #231 (with alpine in mind) dracut is not an option

**Comment by davidcassany** [comment]
In fact I'd like to make it part of the immutable rootfs package, which in turn has little dependencies with dracut and systemd, they are mostly used to order scripts execution at boot but without strong dependencies, it should be easy to use the immutable rootfs scripts out of dracut/systemd context I believe.
