### ISSUE TITLE
Remove hardcoded architecture references

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#475]
## Action items
- [ ] Find out if we have hardcoded architectures in the packages (`x86_64`, `amd64`, ..)
- [ ] Replace the hardcoded architecture with templating where it makes sense

**Comment by Itxaka** [comment]
@mudler are we thinking here to have arch per package or have a general arch in values that all the packages inherit from?

**Comment by mudler** [comment]
I think we are going for `arch` in values, I think we had some spare already defined in the packages, but it was not done consistently all over (the `arch` in `definition.yaml` acts like a "default" which is override by the values`
