### ISSUE TITLE
set LUET_PRIVILEGED_EXTRACT to false make our test suite to fail

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#481]
**cos-toolkit version:**

**CPU architecture, OS, and Version:**

**Describe the bug**
At the moment we have enabled privileged extraction: https://github.com/rancher-sandbox/cOS-toolkit/blob/05e150c923fc72c88a74f854c7d831067bdbe058/packages/installer/upgrade.sh#L165
Because it make our test suite to fail, see https://github.com/rancher-sandbox/cOS-toolkit/pull/260 for context.

**To Reproduce**
Disable `LUET_PRIVILEGED_EXTRACT`

**Expected behavior**
To pass our test suite

**Logs**

**Additional context**
https://github.com/rancher-sandbox/cOS-toolkit/pull/260
https://github.com/rancher-sandbox/cOS-toolkit/issues/480

**Comment by Itxaka** [comment]
Althought vagrant user is mentioned in the original issue, there should be no vagrant user at all in the machine because we use user/pass auth:


```
# itxaka @ zeus in ~/projects/cos-toolkit/tests on git:260 x [17:11:57] 
$ vagrant ssh
==> default: The machine you're attempting to SSH into is configured to use
==> default: password-based authentication. Vagrant can't script entering the
==> default: password for you. If you're prompted for a password, please enter
==> default: the same password you have configured in the Vagrantfile.
Password: 
Last login: Tue Aug 10 15:11:50 2021 from 10.0.2.2
Have a lot of fun...
cos:~ # id
uid=0(root) gid=0(root) groups=0(root)
```

**Comment by Itxaka** [comment]
wrong button
