### ISSUE TITLE
Arch specific cache

### ISSUE THREAD

**Issue by dragonchaser** [rancher-sandbox/cOS-toolkit#524]
Change the structure on quay.io to support arch specific caches.

**Comment by mudler** [comment]
I don't seem to find a "rename" repository button on quay. I'd avoid to disrupt (again) the repository public URLs, and would just go by creating the images for the specific arches which are not amd64 (our default), e.g.:

- https://quay.io/repository/costoolkit/build-green-cache
- https://quay.io/repository/costoolkit/build-green-arm64-cache
- https://quay.io/repository/costoolkit/releases-green
- https://quay.io/repository/costoolkit/releases-green-arm64

**Comment by mudler** [comment]
Repositories have been created and write access has been granted to the robot account tied to Github actions
