### ISSUE TITLE
Remove hardcoded arches

### ISSUE THREAD

**Issue by dragonchaser** [rancher-sandbox/cOS-toolkit#525]
Remove all hardcoded arch definitions.
e.g.

- [x] https://github.com/rancher-sandbox/cOS-toolkit/blob/master/scripts/get_luet.sh#L17
- [ ] https://github.com/rancher-sandbox/cOS-toolkit/blob/9ff8323c3ec981b264d33874433829812333bb75/.github/build.yaml.gomplate#L35
- [x] https://github.com/rancher-sandbox/cOS-toolkit/blob/5e4b098f73daeee96e7a50c0f47b4f099fe5ec11/packages/cos-features/features/carrier.yaml#L32
- [x] https://github.com/rancher-sandbox/cOS-toolkit/blob/9af8b3f4e714d4e4d8299ac073d62f8aacbc9566/.github/workflows/build-pr.yaml#L247
- [ ] ...

**Comment by mudlers** [comment]
Re: the values file, there should be a value file for each specific arch we intend to support (green-arm, blue-arm, etc)

**Comment by Itxaka** [comment]
As part of the arm64 story, all of the hardcoded values here were moved to a var linked to the current arch.
