### ISSUE TITLE
Custom U-Boot

### ISSUE THREAD

**Issue by dragonchaser** [rancher-sandbox/cOS-toolkit#526]
For booting non-uefi based arm boards we need a custom u-boot for each board to chainload grub.

This card is about creating a set of script which can be called by #528  which generates u-boot specific versions for each board we want to support.

Current target is RPIs (arm64).

**Comment by dragonchaser** [comment]
Blocked until we have raspberry pis.

**Comment by mudler** [comment]
Unblocking as we have arm64 packages

**Comment by dragonchaser** [comment]
current bootloader implementation lives here: https://github.com/dragonchaser/pi-bootbuilder will be moved to cos-toolkit later. ATM it can chainload from a grub binary blob. grub compilation in the works. (if you need sth special just overwrite `output/EFI/BOOT/grub.cfg`

**Comment by mudler** [comment]
Firmware for RPI3 and RPI4 has been merged, follow ups will be created
