### ISSUE TITLE
Runners for aarch64/armv7

### ISSUE THREAD

**Issue by dragonchaser** [rancher-sandbox/cOS-toolkit#527]
We need to add a couple of custom runners for the arches mentioned, for aarch64 we could go for aws graviton instances.

- [x] Create a generic way to start ARM (v7/hf and aarch64) runners with a Docker image to start the runner in the same environment, and have a oneliner documented to start it and attach it to the cOS repository
- [x] Finding out a location where to run a permanent runner (AWS, internal ... ?, for now it is running on ec2 and attached to the project)
- [x] Setup the github runner and attach it to repository to run arm workflow (default label: `$ARCH, $OS, self-hosted`)

**Comment by mudler** [comment]
we can also use aws aarch64 for arm7 as well

**Comment by mudler** [comment]
We need to talk to @pgonin first, I'm not sure if we can automatically scale graviton instances, so _maybe_ those should be up and running always in the worse case. 

We might get some internal runners, but blocking this since we need some feedback first.

**Comment by mudler** [comment]
Re: the images, we could use qemu-binfmt in GHA to build and push the docker images for arm platform

**Comment by mudler** [comment]
@dragonchaser are you already looking into this one right?

**Comment by dragonchaser** [comment]
Doing some experiments on docker buildx on the side....

**Comment by dragonchaser** [comment]
I have created a docker image wich can be spawned on arm32v7, aarch64 and amd64.
https://github.com/dragonchaser/dockerhub-autobuild/tree/master/ghrunner

**Comment by dragonchaser** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/pull/605
