### ISSUE TITLE
Image-builder for ARM variants

### ISSUE THREAD

**Issue by mudlers** [rancher-sandbox/cOS-toolkit#528]
Depends on #526 

After we have all the packages and U-boot (#526) should be straightforward to create a generic image builder script for arm which creates images ready to be flashed on SD cards and such.

#526 will contain the specific bits for each board, this card is about a generic script which takes the specific u-boot generated for each board and creates a corresponding image for the supported boards (RPI2/3/4) for now

**Comment by mudler** [comment]
This depends on #526 which is currently blocked

**Comment by Itxaka** [comment]
Added on https://github.com/rancher-sandbox/cOS-toolkit/pull/717

We now have raw images for arm64 built on prs, master and release.

**Comment by Itxaka** [comment]
Somehow the change from here was lost :/

**Comment by Itxaka** [comment]
now really closed by https://github.com/rancher-sandbox/cOS-toolkit/pull/735
