### ISSUE TITLE
cOS repositories for ARM64 architectures (green flavor only)

### ISSUE THREAD

**Issue by mudlers** [rancher-sandbox/cOS-toolkit#530]
We need the arm32/64 repositories to be published with all the packages compiled in order to extend our support for ARM.

Docker repositories were created during https://github.com/rancher-sandbox/cOS-toolkit/issues/524. This card is about running the pipelines on the arm workers in order to have all the packages published along with the CI process

### requirements
 - [X] Arm runners arm64
 - [x] Arm compatible workflows for arm64
 - [x] Arms repositories with artifacts published for arm64

**Comment by mudler** [comment]
Blocked as needs #527

**Comment by Itxaka** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/pull/614 merged which brings arm64 workflows (and fixes some packages to be compatible) and arm64 values

**Comment by Itxaka** [comment]
plenty of things merged, but finally published from master: https://quay.io/repository/costoolkit/releases-green-arm64

**Comment by Itxaka** [comment]
Looks like there is currently a lack of support for graviton instances from armv7. According to @kkaempf there may not be much interest in supporting arm32 currently.

I vote for spinning the arm32 stuff into another card in order to refine and check with Darren if there is a need for it and work from there.

@mudler thoughts?

**Comment by mudler** [comment]
> Looks like there is currently a lack of support for graviton instances from armv7. According to @kkaempf there may not be much interest in supporting arm32 currently.
> 
> I vote for spinning the arm32 stuff into another card in order to refine and check with Darren if there is a need for it and work from there.
> 
> @mudler thoughts?

Sounds good, if it's taking more time than expected just let's split it separately and see if it's really needed :+1:

**Comment by Itxaka** [comment]
As this card is now completed Im closing it, moved all armv7 parts into https://github.com/rancher-sandbox/cOS-toolkit/issues/646
