### ISSUE TITLE
Documentation: default oem configuration and how selectively enable them

### ISSUE THREAD

**Issue by bk201** [rancher-sandbox/cOS-toolkit#571]
**cos-toolkit version:** system/cloud-config-0.8+3

**CPU architecture, OS, and Version:**
Linux rancher 5.3.18-59.19-default #1 SMP Tue Aug 3 14:11:23 UTC 2021 (055c4fd) x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**

nameservers are always overridden by the OEM [config](https://github.com/rancher-sandbox/cOS-toolkit/blob/49ef4b14887ba34578f42d0c8afb674dbc2b720e/packages/cloud-config/oem/05_network.yaml#L11-L16) to
```
nameserver 8.8.8.8
nameserver 1.1.1.1
```
The file is not updated automatically to reflect the DNS-server option in the DHCP protocol.

**To Reproduce**

- Create an ISO with cOS-toolkit
- Boot the ISO and make sure there is a DHCP server that can offer IP for eth0 (also including DNS servers)
- After booting, the nameservers in `/etc/resolv.conf` are not what the DHCP server offers.

**Expected behavior**
- The name servers should be updated to what the DHCP server tells the client.

**Logs**

**Additional context**
This is reported on the Harvester side when the user wants to fetch a config from a server that can be only resolved via custom name servers. https://github.com/harvester/harvester/issues/1137

By default, `/etc/resolv.conf` is a symbolic link to `/run/netconfig/resolv.conf`. The later one will be updated by netconfig to reflect what DHCPD offers. If we generate `/etc/resolv.conf` file from OEM config, the link is no longer there.

I'm not sure if this is worth fixing on the cOS side. Maybe it's not an issue for derivatives other than OpenSUSE.

**Comment by mudler** [comment]
While I do see the issue, the cloud-config shipped by default are optional. They are shipped as part of `system/cloud-config` and can be either not installed at all, or just overwrite/removed as necessary while creating the derivative.

But I clearly see here a gap in our docs! :+1:

**Comment by bk201** [comment]
You are right. If we don't need that, we should not install the `system/cloud-config` package. Thanks!
