### ISSUE TITLE
Identify when booting in live mode

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#572]
**Is your feature request related to a problem? Please describe.**
A concise way to identify when we are booting in live mode, like we do for recovery with a sentinel file

**Describe the solution you'd like**
A /run/cos/live_mode populated on boot for live mode

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by davidcassany** [comment]
I am not against of having a sentinel file for this purpose, however this can be already achieved by having a look to kernel parameters. More specific if the parameter  `rd.cos.disable` (it disables the immutable rootfs logic) is present most likely you are in a livecd boot and also it is likely to identify whatever feature you need/miss in a livecd. Finally you can also check for the presence of `root=live:...` in kernel parameters.

I am wondering about the use case of such a livecd sentinel file. Is it for cloud-init?
