### ISSUE TITLE
Selinux packages autobumping fails

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#578]
**Describe the bug**
the Autobump bot doesn't work with `selinux` packages, the version that is bumped is invalid, so probably the hooks to detect the latest version are misplaced

**Expected behavior**
To bump to the correct version

**Logs**/**Additional context**
https://github.com/rancher-sandbox/cOS-toolkit/pull/575
https://github.com/rancher-sandbox/cOS-toolkit/pull/576

**Comment by Itxaka** [comment]
retriggering autobumper to confirm
