### ISSUE TITLE
Can't pin to specified versions because out-of-dated packages are not in the repository

### ISSUE THREAD

**Issue by bk201** [rancher-sandbox/cOS-toolkit#602]
We'd like to have the ability to pin cOS-toolkit packages on specified versions. Because:
- Packages might be removed. e.g.: https://github.com/harvester/harvester/issues/1160
- New packages might include breaking changes and are not tested (from Harvester side).

We can't put a `@version` after packages now because older or removed packages are not indexed in the Green repository.

**Comment by mudler** [comment]
We need to add the ability for @cOS-cibot to retain the old versions when bumping, so treating this as a feature request

**Comment by mudler** [comment]
https://github.com/harvester/harvester/issues/1160 - is about #557 . That's a bug on our side, @davidcassany  we should have added a `provide` to the old `grub` package so it keeps to be pulled in

**Comment by davidcassany** [comment]
Oh damn, shame on me, my bad :pray: Gonna fix that asap.

**Comment by mudler** [comment]
> Oh damn, shame on me, my bad pray Gonna fix that asap.

I forgot that as well, sorry! we probably need to add more test on the `examples` folder, but I suspect that would increment our CI round-up time excessively..

**Comment by mudler** [comment]
This card requires a major rewrite of the autobumper - which is already at its bash limits :)

**Comment by mudler** [comment]
I think we can actually avoid to keep them in the tree, but just rather reuse the ones that we already publish. I'm doing some changes in lue to allow add to repository index directly from metadata files in https://github.com/mudler/luet/tree/create_repo_from_metadata. This would allow us to control which ones are available while updating the repository index by fetching the metadata only of the packages that we would like to keep in.

**Comment by mudler** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/pull/653 should cover most of all cases for now. We can decide later how much to keep in the repository and implement cleanup jobs. 

I'll create a separate card for the autobumper story
