### ISSUE TITLE
grub-config package was renamed

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#604]
**cos-toolkit version:**
0.6.7

**Describe the bug**
grub2-config was introduced in place of grub-config, causing breakage of `grub-config` consumers. We should have added `grub-config` to the `grub2-config` provides in order to handle a smooth switching without any breakage

**To Reproduce**
`luet install -y system/grub-config`

**Expected behavior**
luet to correctly redirect to grub2-config instead

**Additional context**
#602

**Comment by Itxaka** [comment]
while working on this, it seemed like luet was not taking into consideration the names of the provides for the install. Sent a pathc here: https://github.com/mudler/luet/pull/252/
