### ISSUE TITLE
Cleanup CI leftovers from cloud

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#639]
**Is your feature request related to a problem? Please describe.**
Currently if packer/github jobs fails, they might leave resources behind

**Describe the solution you'd like**
A job in the pipeline to cleanup cloud resources, and optionally a scheduled jobs that runs periodically (?)

**Describe alternatives you've considered**
Cleaning them manually

**Additional context**
#631 for internal runners instead

**Comment by Itxaka** [comment]
Done as part of #649
