### ISSUE TITLE
Replace isoscan with a custom dracut script

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#65]
The isoscan script is really simple, we should be capable to provide our own. We could even avoid the "scan" functionality which looks for the iso image at any available device, there is no need for that, we know the device that holds the image

_Originally posted by @davidcassany in https://github.com/mudler/cOS/pull/58#discussion_r585442021_

while isoscan works, it is better to provide a script that doesn't scan at all, as we already know were the img files are (`COS_STATE`).
Also, isoscan forces `cos-upgrade` to remount the `COS_STATE` partition `rw` as it is already mounted in `/run/initramfs/isoscan` after boot.

**Comment by davidcassany** [comment]
It will be fixed once we finalize #103

**Comment by davidcassany** [comment]
Well, I believe it makes sense and #103 would cover it, among other boot time cleanups. I agree it is has a very low prio, so we can close it, what I'd like to not forget is #103, which goes beyond this issue and clean up the boot procedure so it is easier to evolve it or substitute by other tools (it makes the procedure less dependent to dracut).

I am fine by closing or either leaving it open as tech debt. Probably a label for tech debt would make sense.
