### ISSUE TITLE
Resizing fs with Cloud-init layout plugin

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#661]
**Is your feature request related to a problem? Please describe.**
The layout plugin correctly resizes partition, but it doesn't resize the fs https://github.com/mudler/yip/blob/d7c41b44b3460c63349972949b48e9b8ab31bb33/pkg/plugins/layout.go#L73

**Describe the solution you'd like**
To also resize the partition

**Describe alternatives you've considered**
Calling resizefs manually

**Additional context**

**Comment by Itxaka** [comment]
Blocked until a new yip is released and we can depend on it.
