### ISSUE TITLE
Enhance cloud-init execution output

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#662]
**Is your feature request related to a problem? Please describe.**
When having errors in parsing cloud-init file, it's hard to tell which files have issues. For example, from the following output:

```
ERRO[0000] fatal error: 1 error occurred:
	* yaml: line 8: did not find expected key
``` 
It's hard to tell which is the file causing the error

**Describe the solution you'd like**
A more informative output, including the file which is failing to load

**Describe alternatives you've considered**

**Additional context**

**Comment by Itxaka** [comment]
@ibuildthecloud Can we get an example of the file you were testing that fails so I can reproduce it?
