### ISSUE TITLE
arm64 installation isos

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#676]
**Is your feature request related to a problem? Please describe.**
A way to install cOS derivatives with an arm64 ISO

**Describe the solution you'd like**
An equivalent to what we have for x86_64 for arm64. An installer iso which allows to install cOS or the derivative, with the same GRUB configuration and active/passive mechanism.

**Describe alternatives you've considered**

**Additional context**
#496

**Comment by Itxaka** [comment]
As part of #711 we are now generating the iso as part of CI

**Comment by mudler** [comment]
a post mortem from my side here, seems with https://github.com/rancher-sandbox/cOS-toolkit/pull/711/files we added the ISO for PRs but not for master :man_facepalming:

**Comment by Itxaka** [comment]
yes, Im working on it at the moment as a separate Patch as it requires more changes to templates :D

Expect a PR in 5 seconds

**Comment by Itxaka** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/pull/716
