### ISSUE TITLE
ci: Add automated tests for arm64

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#733]
add tests for arm64 (at least smoke, and one upgrade test) on virtualized env if possible.

## Action Items

- [x] find out if we can run the tests as we do for x86_64 on graviton instances, or implement the required addition/changes to run the suite
- [x] select a small subset of the x86_64 testsuite and add it to our CI as a start. Smoke and upgrade tests should be sufficient for now

**Comment by Itxaka** [comment]
does this also covers raw image or do we think of that as a separate thing?

**Comment by mudler** [comment]
> does this also covers raw image or do we think of that as a separate thing?

the raw image tests are fairly small, so should be part of this card if possible

**Comment by Itxaka** [comment]
qemu packer box and images are now being built as part of the CI - ONLY PRs for now. 

This is the first step if we want to be able to run vagrant for the tests, both with ginkgo or with vagrant itself.

**Comment by Itxaka** [comment]
I have a current branch which uses vagrant with the libvirt provider to bring up an aarch64 machine, should not matter the arch below.

Currently having issues with it but they are not blockers, just leaving them here so they are documented.

 - No serial output -> we need to set the nvram for uefi -> if we set the nvram then we cant destroy the machines via vagrant as per: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1027 and https://github.com/fog/fog-libvirt/pull/102
 - On machine reboot any ssh forwarding is lost. We can still get the ip from `vagrant ssh-config` but we would need to adapt the tests to do this *on each reboot* as the IP also changes on reboot.

**Comment by Itxaka** [comment]
After some heavy testing this is practically impossible on our current setup.

 - Running tests on ubuntu runners -> Slow as hell, about 15 minutes just to set the instance up and another 5 minutes until the test facility first connects to the instance. After each reboot of the instance it would take between 5/7 minutes to reconnect thus making some tests take about an hour or more.
 - Running tests on macos runners -> Impossible, libvirt is not supported on macos so networking fails
 - Running tests on our runner -> Same as ubuntu runners, no kvm, slow as hell.

I dont see an easy choice in here to tests this. Either a baremetal with kvm is available as a runner so we can speed up the tests or there is another way we can sideload the iso/raw disk/qemu image into a aarch64 machine directly.

@kkaempf any idea if there is an arm64 machine laying around for us to use as a ci runner? :D

**Comment by mudler** [comment]
Could at least a simple upgrade test run in a virt environment? even if that would take around 30/40 mins, that would be acceptable for a sanity test

**Comment by Itxaka** [comment]
> Could at least a simple upgrade test run in a virt environment (like ubuntu)? even if that would take around 30/40 mins, that would be acceptable for a sanity test

I would say that its not worth it on its current state as it require way too many hacks to make it work decently and the tests ends up pretty flaky from my testing.

We could move the arm64 testing to some other place like cirrus ci which support kvm thougth. Still the testing framework needs adjustments and the cleanup is a mess, but less with ephemeral runners :)

**Comment by Itxaka** [comment]
Seems like there is another way... there is this a1.metal instances that expose kvm and are arm64 based, sooo...we could have one of those.

They are a bit expensive thought, like 0,50$ per hour which means its 12$ a day so  360$ a month.

Sure, we could schedule them an only have them available under business hours, so that would go to 80$ per month...

**Comment by Itxaka** [comment]
a1.metal performance is abysmal btw...

**Comment by kkaempf** [comment]
> 
> They are a bit expensive thought, like 0,50$ per hour which means its 12$ a day so 360$ a month.
> 
> Sure, we could schedule them an only have them available under business hours, so that would go to 80$ per month...

@pgonin 👆🏻

**Comment by mudler** [comment]
We have test running on CI in a virtualized machine https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/1328267611. It is slow but times are acceptable as are inline with amd64. Creating a follow-up for the test suites to run
