### ISSUE TITLE
ci: testing the installer

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#734]
Currently we just run a shallow test on the installer: the test process starts by creating a vagrant image by using `cos-installer`.

It would be nice to have a test suite for `cos-installer`, as likely would also help with #581 and increase the test coverage area.

## Action items

- [ ] Find out a way to run automated test for the installer ( vagrant, insert iso on runtime and reboot )
- [ ] Create a simple test suite to leverage the installer options ( e.g. test `after-install-chroot` hook )

**Comment by Itxaka** [comment]
Doesn't cover all tests but it's a start and a framework to cover more in the future.

I will create s follow up card with some of the expected tests.

One thing though is that efi testing seems to take waaaay longer for some weird reason...but most of the time spent there is during cos-install for some weird reason. I will create another card to follow up on that, in case it's just not just a coincidence but something wrong with the installer. Both run in macos and the virtual drives should be the same, but the times are veeeery different (2 minutes Vs 8/13 minutes!)
