### ISSUE TITLE
Improve the ability to debug kernel issues

### ISSUE THREAD

**Issue by yasker** [rancher-sandbox/cOS-toolkit#751]
**Is your feature request related to a problem? Please describe.**
Harvester is having a kernel issue. https://github.com/harvester/harvester/issues/1342 
There is no best practice or easy way for the kernel engineer to debug it.

**Describe the solution you'd like**
We need to take what is needed to debug a kernel problem into consideration when building the OS.

Not sure if this issue is more related to a certain OS or the toolkit.

**Comment by mudler** [comment]
@yasker do you have anything specific in mind? The only things that come up in my mind are all changes that have to be done from a derivative perspective, like adding kdump and enabling the kdump service

**Comment by yasker** [comment]
@mudler We need to consult kernel team for this. I have a few things in mind listed in https://github.com/harvester/harvester/issues/1343 but I am not knowledgeable enough to make recommendations.

**Comment by yasker** [comment]
One of the biggest pain points we have right now, is due to the root partition cannot be changed, we cannot install recommended tools to the OS to help with the kernel debugging (https://github.com/harvester/harvester/issues/1342#issuecomment-932309680). So we either pre-install tools (based on kernel team's recommendation), or have a way to temporarily install more packages/tools on the disk.

**Comment by mudler** [comment]
> One of the biggest pain points we have right now, is due to the root partition cannot be changed, we cannot install recommended tools to the OS to help with the kernel debugging ([harvester/harvester#1342 (comment)](https://github.com/harvester/harvester/issues/1342#issuecomment-932309680)). In fact, if additional tools are required for any system-level debugging, we won't be able to do it. So we either pre-install tools (based on kernel team's recommendation), or have a way to temporarily install more packages/tools on the disk.
> 
> cc @ibuildthecloud @jeff-hobbs

It is possible to boot the system in RW capabilities, see: https://rancher-sandbox.github.io/cos-toolkit-docs/docs/reference/troubleshooting/#kernel-parameters.

And is also possible to actually do changes to the system image too, as documented here: https://rancher-sandbox.github.io/cos-toolkit-docs/docs/customizing/runtime_persistent_changes/ but you need `utils/installer` at least at version 0.17

**Comment by janeczku** [comment]
Is it possible to persist changes to `/etc/cos/bootargs.cfg` by booting the system in RW mode (`rd.cos.debugrw`). And where is the source file for `/etc/cos/bootargs.cfg`  found once the system is booted RW ?

**Comment by mudler** [comment]
> On which path is the root image mounted RW once the system is booted with `rd.cos.debugrw` ? And does this allow persisting changes to `/etc/cos/bootargs.cfg` ?

The whole system would boot in rw mode, so any change you would do to the system while booting with `rd.cos.debugrw` will be persistent

**Comment by mudler** [comment]
Awesome, thanks!
