### ISSUE TITLE
Failure to install with ISO

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#772]
**cos-toolkit version:**
b50f75fede91bd092a06114ccd3dd18b520de29e

**CPU architecture, OS, and Version:**
Hetzner dedi 

**Describe the bug**
running `cos-installer --iso <URL>` installed an empty image (only the layout of the image was present, but with no content)

**To Reproduce**
Boot a live from iso and try to run the installer with a different iso URL. Preferably the bootable system has not to be cOS.

**Expected behavior**

**Logs**
N/A

**Additional context**
I don't have logs anymore, but it happened when trying to install cOS on hetzner. The ISO was correctly downloaded but the content of the active/passive where empty, only the layout was properly created.

Relates to #734 , as this is not tested automatically

**Comment by Itxaka** [comment]
I just tried this and it worked out of the box.

Built master as iso, booted from qemu with that iso, and used the `--iso` to point it to the same locally served iso. Everything worked as expected, iso was downloaded and extracted properly.

Any info on what isos you used @mudler ?

**Comment by mudler** [comment]
> I just tried this and it worked out of the box.
> 
> Built master as iso, booted from qemu with that iso, and used the `--iso` to point it to the same locally served iso. Everything worked as expected, iso was downloaded and extracted properly.
> 
> Any info on what isos you used @mudler ?

I think it was https://github.com/rancher-sandbox/cOS-toolkit/releases/tag/v0.6.8, but if we can't reproduce it anymore we should close this issue

**Comment by mudler** [comment]
Closing this, we are about to add specific tests for this scenario in #734
