### ISSUE TITLE
Sigstore support

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#808]
**Is your feature request related to a problem? Please describe.**
Currently we have the mtree plugin which allows to create manifests that can be used to match against installed packages. Although we want to provide a solution that can secure the full supply chain by also signing packages

**Describe the solution you'd like**
[cosign](https://github.com/sigstore/cosign) support. This ideally should happen when:

- [x] we install packages with `luet install` when a user creates the derivative 
- [x] we build packages, allowing to check with sigstore the source images before continuing to build. And push during repository creation/package building the signed artifacts
- [x] when we run manual upgrades with `cos-upgrade`. When we give either a container image as input or a set of packages
- [x] Document the vars used
- [x] Document on derivative pages how to use the verify so derivatives can verify that our images are signed properly

Note that all the followings could be provided in form of a plugin/extension, as we do with mtree, and the above functionalities should be optional for the user. 

 # follow up
 - [x] https://github.com/rancher-sandbox/luet-cosign/issues/6
 - [x] add cosign signature verification to a derivative example repo like c3os for packages coming from cos-toolkit -> https://github.com/mudler/c3os/pull/1

**Comment by Itxaka** [comment]
Docs are provided. https://github.com/rancher-sandbox/cos-toolkit-docs/pull/54
Meta package is provided. https://github.com/rancher-sandbox/cOS-toolkit/pull/833
Examples are updated. https://github.com/rancher-sandbox/cOS-toolkit/pull/833

**Comment by Itxaka** [comment]
Example of checking cos signatures in a derivative -> https://github.com/mudler/c3os/pull/1

**Comment by Itxaka** [comment]
skip packages/repos is provided on https://github.com/rancher-sandbox/luet-cosign/releases/tag/v0.0.8
