### ISSUE TITLE
Recovery sets the wrong os-release data

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/cOS-toolkit#843]
**cos-toolkit version:**
master

**CPU architecture, OS, and Version:**
N/A

**Describe the bug**
When resetting from recovery, the os-release is filled based on the recovery data, which makes the active partition os-release wrong, i.e.:

```
cos:~ # cat /etc/os-release 
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/mudler/cOS/issues"
DOCUMENTATION_URL="https://github.com/mudler/cOS"
HOME_URL="https://github.com/mudler/cOS"
ID="cOS recovery"
NAME="cOS recovery"
PRETTY_NAME="cOS recovery v35.0.0"
VERSION="35.0.0"
```

Both name and version are propagated from the recovery data into the new active partition, thus having wrong values in there.

**To Reproduce**
cos-reset from recovery, check os-release

**Expected behavior**
cos-reset to set the proper data or at least keep the existing data if possible?

**Logs**

**Additional context**

**Comment by mudler** [comment]
I'm not sure if this can be considered a bug. It is working as intended: It's up to who is building the derivative if they want to specify a different versioning schema, or just reuse standard images for recovery. 

I think fiddling with images data would invalidate the upgrade process, as we would start to actively modify things

**Comment by Itxaka** [comment]
what about the base os version reporting in a cluster? That could lead to problems with different versions on nodes that have been reset VS installed nodes. Like that is my main concern with this, that it could lead to confusion, thus invalidating one of the cos points of having an homogenized cluster of nodes.

Maybe this is already written down somewhere in the docs thought, that would be enough for me, that people are aware of this issue/non-issue.

**Comment by mudler** [comment]
> what about the base os version reporting in a cluster? 

Running a cos-reset would report back the original installed version then. It is totally optional to have a separate recovery, and it's a derivative designer choice. 

By default the recovery is created from the first installation, so it's the same image that behaves differently from the context (again, designer choice) we have docs covering how to specify a separate one https://rancher-sandbox.github.io/cos-toolkit-docs/docs/creating-derivatives/build_iso/#separate-recovery

**Comment by Itxaka** [comment]
Seems fair enough to me, closing this then.
