### ISSUE TITLE
Expand tests for installer

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/cOS-toolkit#859]
**Is your feature request related to a problem? Please describe.**
Currently we have minimal tests for installer, we should expand them

**Describe the solution you'd like**
Expanding tests for the installer

**Describe alternatives you've considered**
not testing anything and living la vida loca

**Additional context**
The installer tests already has some test descriptions on them as guidance.

**Comment by mudler** [comment]
#581 contains already a small list of scenarios which aren't currently covered, but I guess most likely we would like to cover what we have documented: https://rancher-sandbox.github.io/cos-toolkit-docs/docs/getting-started/install/

**Comment by Itxaka** [comment]
Part of this is done, missing installer options

    –iso (How to serve the iso?)
    –poweroff (Can probably be only tested on bios)
    –no-format (Requires a pre-format)
    –docker-image
    –debug ( needed?)
    –no-verify
    –no-cosign

**Comment by Itxaka** [comment]
docker-image is probably the most important currently and should be straightforward to implement
