### ISSUE TITLE
Installer tests on efi takes 3 times more than normal bios ones

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/cOS-toolkit#860]
**cos-toolkit version:**
master

**CPU architecture, OS, and Version:**
N/A

**Describe the bug**
on testing the cos-installer we have 2 paths, efi and bios. We create a virtualbox VM with either bios or efi as starting point to run the proper path test. Cos installer on bios machines takes about 2 to 3 minutes while cos-installer on efi takes between 6 and 12 minutes somehow??
Seems pretty consistent and the base os is the same for the VMs, as its the virtualized hardware so it should not be as clear cut as it seems to be.

This needs to be checked a bit deeper to see if we have something wrong on the installer or its simply a difference on the efi/bios path that just makes any extra steps that take more time (i.e. crete more partitions, copy extra files, etc...)

**To Reproduce**
Check CI for the `test-{squashfs,nonsquashfs}-installer-{efi,bios}` job to see the differences, enable timestamps on the log, check the step `Running cos-installer` to see how much it took

**Expected behavior**
Same time for both, maybe a bit longer on efi if we run extra steps. Not 3x time difference unless we do something completely different.

**Logs**
Check job https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/1445978336 for an example.

BIOS:
```
Thu, 11 Nov 2021 01:15:49 GMT STEP: Running the cos-installer
Thu, 11 Nov 2021 01:17:55 GMT STEP: Reboot
```

EFI:
```
Thu, 11 Nov 2021 01:24:47 GMT STEP: Running the cos-installer
Thu, 11 Nov 2021 01:32:03 GMT STEP: Store CD location
```

**Additional context**

**Comment by mudler** [comment]
Even if slow, I don't think should be marked as "bug". Things are still working, as the installation succeeds, or I'm missing something?

**Comment by Itxaka** [comment]
Yeah it works, but...why does it take so much time? Maybe it's a big, maybe it's a feature. I don't care what the card is classified as, as long as I can follow up and she'd some light on what's going on :)

Maybe some investigation or follow up label would be better

**Comment by Itxaka** [comment]
couple of things take a bit more like grub install and parted, but they are within the limits of what one would consider acceptable. I dont think cos-installer has any inherent issues with efi, its just a bit slower and that sums at the end after all the steps.
