### ISSUE TITLE
Create multiple partitions might fail

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#887]
Seems there is a flakyness while creating multiple repository in sequence in a disk. Seems `yip` fails to find the partitions after creation 

**cos-toolkit version:**
Applies to yip from https://github.com/rancher-sandbox/cOS-toolkit/commit/108a64bcf7ed8ee106d8aa770982871e7c7a2c0c

**Additional context**
https://github.com/harvester/harvester/issues/1583

**Comment by Itxaka** [comment]
gofmthttps://github.com/mudler/yip/pull/27

**Comment by mudler** [comment]
Reopening as we are still seeing this issue

**Comment by Itxaka** [comment]
https://github.com/mudler/yip/releases/tag/0.9.25 should fix this

**Comment by Itxaka** [comment]
Harvester folks closed their issue as resolved, they tested positive and negative with great results, so closing this.

https://github.com/harvester/harvester/issues/1583
