### ISSUE TITLE
`elemental install $device`

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#905]
Part of #108 

port current `cos --install` code to the CLI created in #881 and consume it in place of `cos-installer` (point the wrapper to the elemental-cli).

- [x] #1005
- [x] #962
- [x] #963
- [x] #964
- [x] #965
- [x] #1019
- [x] #1020

See: https://github.com/maxbrunsfeld/counterfeiter

**Comment by mudler** [comment]
Install skeleton: https://github.com/rancher-sandbox/elemental-cli/pull/2
Partitioning: https://github.com/rancher-sandbox/elemental-cli/pull/3
