### ISSUE TITLE
Documentation: docs website

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#92]
"landing page" documentation

- [ ]     a tag line
- [ ]     how to ~install~build
- [ ]     a description of the target audience
- [ ]     some use cases and link to sample repositories
- [ ]     link to github docs directory

**Comment by kkaempf** [comment]
The initial request is for "landing page" documentation

- a tag line
- how to install
- a description of the target audience
- some use cases
- link to github docs directory

**Comment by Itxaka** [comment]
Also have a look at https://github.com/rancher-sandbox/hypper.io to clone it

**Comment by kkaempf** [comment]
or https://github.com/epinio/epinio.io :wink:

**Comment by mudler** [comment]
https://github.com/rancher-sandbox/cos-toolkit-landing-page 

https://rancher-sandbox.github.io/cos-toolkit-landing-page/ 

We miss a logo and a name but we are almost there :)
