### ISSUE TITLE
GRUB menu rebranding doesn't work after upgrading

### ISSUE THREAD

**Issue by bk201** [rancher-sandbox/cOS-toolkit#928]
**cos-toolkit version:**
utils/installer-0.21.1

**CPU architecture, OS, and Version:**
Linux node1 5.3.18-59.34-default #1 SMP Thu Nov 11 12:18:45 UTC 2021 (a2a53aa) x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
In Harvester we add `GRUB_ENTRY_NAME="Harvester {VERSION}` to `/etc/os-release` to display the name in GRUB menu entries. e.g.,
```
NAME="Harvester"
ID="harvester"
ID_LIKE="suse opensuse"
VERSION_ID="20211130"
PRETTY_NAME="Harvester 1.0.0-rc1"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/harvester/os2/issues"
HOME_URL="https://github.com/harvester/os2"
GRUB_ENTRY_NAME="Harvester 1.0.0-rc1"
```

After upgrading the OS with a new image by calling `cos upgrade`, the GRUB menu entry still use the old one:

```
node3:~ # cat /etc/os-release
NAME="Harvester"
ID="harvester"
ID_LIKE="suse opensuse"
VERSION_ID="20211130"
PRETTY_NAME="Harvester b62f9f8-dirty"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/harvester/os2/issues"
HOME_URL="https://github.com/harvester/os2"
GRUB_ENTRY_NAME="Harvester b62f9f8-dirty"

node3:~ # cat /run/initramfs/cos-state/grub_oem_env
# GRUB Environment Block
# WARNING: Do not edit this file other than by grub2-editenv
default_menu_entry=Harvester v1.0.0-rc1
##################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
```
**To Reproduce**

Upgrade a cOS derivative with a new image which has a different `GRUB_ENTRY_NAME` option in `/etc/os-release`.
**Expected behavior**

The GRUB menu should be rebranded.

**Logs**

**Additional context**

- Looks like `rebrand` is not performed in `upgrade` path.
- I can workaround by remounting `/run/initramfs/cos-state/`  in rw mode and run the `grub2-editenv /run/boot/grub_oem_env set default_menu_entry="$grub_entry"` command.

**Comment by yasker** [comment]
Hi @bk201 , I think we need this for a certain version, not upstream right? What’s the version we need this fix to be backport to?

**Comment by bk201** [comment]
Yes, similar to this issue: https://github.com/rancher-sandbox/cOS-toolkit/pull/937

> Hi @bk201 , I think we need this for a certain version, not upstream right? What’s the version we need this fix to be backport to?
> 
> Update: I believe it’s `0.21.x`

**Comment by mudler** [comment]
So I did have a :eyes: and I think we didn't call rebrand intentionally after upgrade. 

As the branding is set during install in the first place, it shouldn't be required during the upgrade but should persist the one during install. Is the problem surfacing in the first setup from the beginning? is the menu correctly displayed before upgrade?
 we try to keep the core as minimal as possible in the various parts (upgrades/install/reset, etc) but extensible (maybe an after-upgrade hook could do the trick?)

I can do the change of course, but I'd like to understand what's the use case at hand here

**Comment by bk201** [comment]
@mudler The menu is correct before an upgrade. The rebranding during the installation time works well and it also works well after an upgrade.

The problem is we also include the version (e.g. `Harvester 1.0.0-rc1` in the `GRUB_ENTRY_NAME`). After an upgrade, GRUB still displays the old entry name in the grub_oem_env file (but the running OS's `/etc/os-release` file contains a newer version: e.g. `Harvester 1.0.1`).

**Comment by mudler** [comment]
Ok, I have understimated it. A simple call to rebrand is not enough as it would apply the changes from the system which is upgrading, and not the one which is being upgraded to. I've opened https://github.com/rancher-sandbox/cOS-toolkit/pull/959 as it slighlty changes things and added a test case for it. Waiting on CI to confirm all looks good

**Comment by bk201** [comment]
Just for a record, here is my current workaround: https://github.com/harvester/harvester/pull/1635/commits/231f2b2aa4938b3dbdaf95848cd3b079dc1ec184#diff-43150fc991c91f07946cd41d2d0311c58a9f5deb4c061e1cf3ed11b9cd3dde3bR223-R227
