### ISSUE TITLE
User-data cloud-init files from cloud sources

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#93]
A mechanism similar to https://github.com/rancher/k3os#k3osdata_sources for `yip` where the user can define a list of cloud sources where to pull the cloud-init configuration from. 

From the list above, I would add:

- git (public/private repository)
- usb

See also https://github.com/linuxkit/linuxkit/tree/master/pkg/metadata and https://github.com/rancher/k3os/commit/016bd8ca3d5b73609c06e358ec01f520feae1a2f for an example implementation

WIP branch here: https://github.com/mudler/yip/tree/datasources

Let's also test the providers we can:

- [x] aws
- [x] digitalocean

**Comment by davidcassany** [comment]
I did some further tests with Digital Ocean. 

Given a yaml file like:
```yaml
name: "Testing digital ocean userdata provider"
stages:
  test:
    - datasources:
      - type: "digitalocean"
```

Userdata of the droplet was:

```json
{
  "customfiles": {
    "entries": {
      "data": {
        "perm": "0644",
        "content": "This is some custom data"
      }
    }
  }
}
```
Running `yip` on digital ocean droplet from the folder containing the yaml file with command:

`>$ yip -s test $(pwd)`

Produces the following files under `/run/config`:

```shell
> ls -l /run/config/
total 28
drwxr-xr-x 2 root root  60 Apr 26 11:54 customfiles
-rw-r--r-- 1 root root  32 Apr 26 11:54 hostname
-rw-r--r-- 1 root root   9 Apr 26 11:54 id
-rw-r--r-- 1 root root  10 Apr 26 11:54 private_ipv4
-rw-r--r-- 1 root root  12 Apr 26 11:54 provider
-rw-r--r-- 1 root root  14 Apr 26 11:54 public_ipv4
-rw-r--r-- 1 root root   4 Apr 26 11:54 region
drwxr-xr-x 2 root root  60 Apr 26 11:54 ssh
-rw-r--r-- 1 root root 143 Apr 26 11:54 userdata

> cat /run/config/customfiles/data 
This is some custom data
```

**Comment by davidcassany** [comment]
The current status mimics the behavior of [linuxkit/linuxkit](https://github.com/linuxkit/linuxkit) metadata tool. I'd say this is not the end goal but it opens the door to start testing and refining the exact behavior we aim for.

IMHO this approach of embedding config files in a json like format is not bad, but it turns to be cumbersome if the only purpose of it is actually providing a clould-init yaml file. I think parsing the user data as a yaml, if possible, and store it as an additional cloud-init file to some in-advance known location might be a better approach.
