### ISSUE TITLE
Move build jobs to self-hosted workers

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#939]
**Is your feature request related to a problem? Please describe.**
See #917,  amd64 github workers are running out of space, plus internal workers form a trusted environment where to build packages.

**Describe the solution you'd like**
self-hosted workers to build packages

**Additional context**

## Action items
- [x] Find requirements in terms of HW capabilities (CPU, RAM, HDD disk, VM count) for amd64 runners
- [x] Compare to what we have in GHA in term of resources for parallel jobs
- [x] Find machines where to host GH runners (ping @kkaempf )
- [x] Deploy (or have them maintained?) see example here https://github.com/rancher-sandbox/cOS-toolkit/wiki/Github-runner-on-k8s
- [x] Work out pipeline changes and attach only `build` jobs to self-hosted workers
- [x] Let PR run on public runners and have a label to override that

**Comment by kkaempf** [comment]
Internal (and 'beefy') hardware is secured. :wink:
