### ISSUE TITLE
Firmware not working on rpi4 (cos not booting)

### ISSUE THREAD

**Issue by dragonchaser** [rancher-sandbox/cOS-toolkit#940]
When booting on rpi4 u-boot and grub are properly booting, but the process gets stuck at:
```
EFI stub: Exiting boot services and installing virtual address map...
```

I assume this is due to a firmware bump on the repo.

**Comment by kkaempf** [comment]
Asking @afaerber for advise here 🥺

**Comment by kkaempf** [comment]
The problem is the origin of the firmware files, not how cOS-toolkit boots the image.

If I replace the cOS firmware files with one's from Leap-15.3-JeOS...-RaspberryPi (without adding or removing a file), the resulting image (resp. SD-card) successfully boots on RPi3 **and** RPi4

**Comment by mudler** [comment]
maybe as @gmoro noted, maybe we can use FW from Leap @dragonchaser ? 

https://download.opensuse.org/distribution/leap/15.3/repo/oss/aarch64/u-boot-rpiarm64-2021.01-5.1.aarch64.rpm

**Comment by mudler** [comment]
@dragonchaser are you working on it, right?

**Comment by dragonchaser** [comment]
https://github.com/dragonchaser/cOS-toolkit/tree/try_leap_firmware pr will be created today as soon it is verified that it works on rpi3
