### ISSUE TITLE
`elemental cloud-init`

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#942]
- [x] reuse `yip` as a library
- [x] Cut a new elemental-cli version (https://github.com/rancher-sandbox/elemental-cli/releases/tag/v0.0.2)
- [ ] Integrate `elemental cloud-init` in place of `yip` inside `cOS-toolkit` #976

**Comment by mudler** [comment]
Still not done yet. missing integration inside cOS toolkit

**Comment by Itxaka** [comment]
Sorry, I dont understand why github says that I closed this ????

**Comment by mudler** [comment]
Neither do I :sweat_smile:
