### ISSUE TITLE
backport the NVME fix to cOS-installer version 0.21 

### ISSUE THREAD

**Issue by guangbochen** [rancher-sandbox/cOS-toolkit#946]
backport the [NVME fix](https://github.com/rancher-sandbox/cOS-toolkit/pull/933) to cOS-installer version 0.21 ? The cOS-installer we're using right now in Harvester is 0.21.1 and we're facing some compatibility issues while upgrade it to the latest version. 
preferred to have a 0.21.2 instead of a locally-patched version. We're hoping to fix this issue before the end of this week, so I think we still got some time. thanks

cc @johnliu55tw

**Comment by mudler** [comment]
https://github.com/rancher-sandbox/cOS-toolkit/pull/937 backports https://github.com/rancher-sandbox/cOS-toolkit/pull/933 and https://github.com/rancher-sandbox/cOS-toolkit/issues/938 to a new `0.21.2` installer version
