### ISSUE TITLE
Verified images

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#95]
A mechanism that verifies the images consumed by the running system. When we do installation and upgrades, we recompose an img file from a docker image which is pulled. The docker image itself is verified with DCT and checksum verification, but the image that we create to boot from it's not. The issue is about finding a strategy to sign the content which is actually being used to boot. This can be done:

- By either uploading separate .img file into standalone images (retrieved by metadata informations?) which is directly consumed (no reconstruction needed) or 
- by another mechanism that is able to verify that the img files we are reconstructing are exactly the same from the docker ones. See https://github.com/moby/moby/blob/master/pkg/tarsum/tarsum.go#L4 as an example

This mechanism should be used by the standard upgrade channel, while **could** be ignored when passing by a docker image (e.g. for local development iteration)

See also: https://artifacthub.io/packages/tbaction/tinkerbell-community/archive2disk

Sub-Issues

- [x] #107
- [x] #113
- [x] #126
- [x] #175

**Comment by Itxaka** [comment]
all done!
![dancing-duck](https://user-images.githubusercontent.com/1447686/120983255-d1d06d80-c779-11eb-9036-f7efb1aa5cdd.gif)
