### ISSUE TITLE
SElinux policies fails to build

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#960]
**cos-toolkit version:**
https://github.com/rancher-sandbox/cOS-toolkit/commit/bca5b092230d419ead0e83676a27769d73ab5e34

**CPU architecture, OS, and Version:**

**Describe the bug**
Seems both selinux/k3s and selinux/rancher fails to build locally with:

```
 INFO   #9 55.16 Resolving package dependencies...
 INFO   #9 55.24 2 Problems:
       #9 55.24 Problem: the installed shadow-4.8.1-2.43.x86_64 requires 'libsemanage.so.1()(64bit)', but this requirement cannot be provided
       #9 55.24 Problem: the to be installed container-selinux-2.171.0-lp153.17.7.noarch requires 'selinux-policy >= 20211111-lp153.114.7', but this requirement cannot be provided
       #9 55.24 
       #9 55.24 Problem: the installed shadow-4.8.1-2.43.x86_64 requires 'libsemanage.so.1()(64bit)', but this requirement cannot be provided
       #9 55.24  Solution 1: Following actions will be done:
       #9 55.24   deinstallation of shadow-4.8.1-2.43.x86_64
       #9 55.24   deinstallation of python-azure-agent-2.2.49.2-3.20.1.noarch
       #9 55.24  Solution 2: keep libsemanage1-3.0-1.27.x86_64
       #9 55.24  Solution 3: break shadow-4.8.1-2.43.x86_64 by ignoring some of its dependencies
       #9 55.24 
       #9 55.24 Choose from above solutions by number or skip, retry or cancel [1/2/3/s/r/c/d/?] (c): c

```

**To Reproduce**
sudo make PACKAGES="selinux/rancher selinux/k3s" build

**Expected behavior**
Packages to build

**Comment by Itxaka** [comment]
This also happens with a plain leap 15.3 system and the same repo

**Comment by Itxaka** [comment]
I talked with Johannes Segitz (maintainer of the security:SELinux packages on obs), seems like this is a known issue due to `libsemanage wasn't properly versioned in v1,that is now changed but unfortunately this is the fallout`

So we need to workaround on this until 15.4 is released (on June I think?)

**Comment by Itxaka** [comment]
There is a workaround that I found that its...kind of crappy

It requires removing the `shadow` package, installing everything as usual, then installing shadow back ignoring its dependencies (`libsemanage.so.1`) and creating a link from `libsemanage.so.2` to `libsemanage.so.1` so it uses the newer `libsemanage`.

I mean...that seems to work and shadow seems to work but...Im not sure what are the ramifications of this...

**Comment by Itxaka** [comment]
any ideas @mudler @davidcassany @dragonchaser ? Other than trying to break shadow or skipping selinux for now :(

**Comment by Itxaka** [comment]
actually thinking about this, the final artifact results in only the policies, doesnt it? do we even need all this prelude stuff??

**Comment by mudler** [comment]
> There is a workaround that I found that its...kind of crappy
> 
> It requires removing the `shadow` package, installing everything as usual, then installing shadow back ignoring its dependencies (`libsemanage.so.1`) and creating a link from `libsemanage.so.2` to `libsemanage.so.1` so it uses the newer `libsemanage`.
> 
> I mean...that seems to work and shadow seems to work but...Im not sure what are the ramifications of this...

In theory, none, the consumers are going to just take the rpm result

> actually thinking about this, the final artifact results in only the policies, doesnt it? do we even need all this prelude stuff??

IF we can force the RPM install, I think we should be fine too..

**Comment by Itxaka** [comment]
Interesting, it seems like repo was providing a shadow package to avoid this issue. It has been restored now, so when its finished building and being published this issue will be fixed. All thanks to Johannes :)

**Comment by Itxaka** [comment]
link to the package it fails to build due to lint issues, but they are already looking into it: https://build.opensuse.org/package/show/security:SELinux/shadow

**Comment by Itxaka** [comment]
shadow package is now republished, repo installs correctly and selinux packages build again.
