### ISSUE TITLE
Keep new files below /etc

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#97]
We need a mechanism (by default on, but that can be switched off) to turn `/etc` semi-permanent: e.g. we discard file delta changes, but we keep new file additions.

**Comment by davidcassany** [comment]
Something simple to implement and to experiment with is a multilayer overlayfs mount point for `/etc`.

The ephemeral `/etc` we have now is a simple overlayfs on tmpfs, in fact the mount command line is:

```
mount -t overlay overlay -o defaults,lowerdir=/etc,upperdir=/run/overaly/etc.overlay/upper,workdir=/run/overlay/etc.overlay/work /etc
```

On lower dir we could stack on top a persistent `/usr/local/etc`, meaning that files included in `/usr/local/etc` would automatically also appear in `/etc` as part of the base overlay. Command would then be:

```
mount -t overlay overlay -o defaults,lowerdir=/usr/local/etc:/etc,upperdir=/run/overaly/etc.overlay/upper,workdir=/run/overlay/etc.overlay/work /etc
```

So one could eventually create new files in `/usr/local/etc` and consume them from `/etc` and `/usr/local/etc` is part of the persistent storage. The problem I see here is what happens one modifications are applied in merged mountpoint but also in lower mountpoint, so for instance we create a file `/usr/local/etc/somethingnew` and then modify the file from `/etc/somethingnew` (at that point the original and modified file are no longer tied). From now on changes on  `/usr/local/etc/somethingnew` are hidden until next reboot.

I find it slightly confusing but it would be a quite clean implementation to actually control which changes of the `/etc` are kept, only changes applied to `/usr/local/etc` would be visible in  `/etc` after reboot, any other changes applied on runtime would be lost.
