### ISSUE TITLE
CI fails publishing cosign signatures

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#975]
Seems master is stuck in publishing cosign signatures at the end of the pipeline. Doesn't seems a sporadic issue as we have retriggered CI multiple times since yesterday.

**Logs**
```
override
 INFO   Image quay.io/costoolkit/releases-green:cos-container-system-0.7.9-17 already present, skipping. use --force-push to override
 INFO   Image quay.io/costoolkit/releases-green:cos-container-system-0.7.9-18.metadata.yaml already present, skipping. use --force-push to override
 INFO   Generating final image quay.io/costoolkit/releases-green:cos-container-system-0.7.9-18 for package  system/cos-container-0.7.9-18
 SUCCESS    Loaded image: /var/tmp/luet/tempimage330365095
 SUCCESS    Pushed image: quay.io/costoolkit/releases-green:cos-container-system-0.7.9-18
  ERROR    Plugin luet-cosign at /usr/bin/luet-cosign had an error: exit status 2
make: *** [make/Makefile.build:106: publish-repo] Error 1
Error: Process completed with exit code 2.
```

**Additional context**
#973 #974

https://github.com/rancher-sandbox/cOS-toolkit/runs/4534197096?check_suite_focus=true

**Comment by Itxaka** [comment]
Started to happen 2 days ago it looks like, according to the last proper publish job: https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/1576405567

No apparent reasons other that exit code 2, 2 patches have been merged to get the luet-cosign logs in case of failure to understand whats happening

**Comment by mudler** [comment]
Seems temporary downgrade to 1.3.x works: https://github.com/rancher-sandbox/cOS-toolkit/runs/4546591562?check_suite_focus=true , so there seems something not still there after the bump to `1.4.x`

**Comment by mudler** [comment]
From logs on a 1.4.1 build, we are hitting:

```
[2021-12-16 10:30:20] Got event: image.pre.push
[2021-12-16 10:30:20] Got event: image.pre.push
[2021-12-16 10:31:02] Got event: image.post.push
[2021-12-16 10:31:02] Signing image: quay.io/costoolkit/releases-green:cos-img-recovery-0.7.9-18
[2021-12-16 10:31:02] Using experimental keyless signing!
[2021-12-16 10:31:02] Got event: image.post.push
[2021-12-16 10:31:02] Signing image: quay.io/costoolkit/releases-green:cos-img-recovery-0.7.9-18
[2021-12-16 10:31:02] Using experimental keyless signing!
[2021-12-16 10:31:03] Error while executing cosign: Generating ephemeral keys...
Retrieving signed certificate...
retrieving trusted root; local cache may be corrupt: creating cached local store: resource temporarily unavailable
panic: error retrieving CT public key

goroutine 1 [running]:
github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier.getCTPub()
	github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go:47 +0x13a
github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier.verifySCT({0xc000d4c000, 0x41e, 0x7c0}, {0xc000d16b40, 0xe6, 0xe7})
	github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go:57 +0x45
github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier.NewSigner({0x2a6a210, 0xc000050180}, {0xc000ad4100, 0xc0005df658}, {0x25c55dc, 0xc00000e020}, {0x258984f, 0x1}, {0x2a240c0, 0xc0002cbec0})
	github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go:79 +0x8d
github.com/sigstore/cosign/cmd/cosign/cli/sign.keylessSigner({0x2a6a210, 0xc000050180}, {0x0, {0x0, 0x0}, {0x0, 0x0}, {0x25bf377, 0x1e}, {0x25b3dda, ...}, ...})
	github.com/sigstore/cosign/cmd/cosign/cli/sign/sign.go:402 +0x1ab
github.com/sigstore/cosign/cmd/cosign/cli/sign.SignerFromKeyOpts({0x2a6a210, 0xc000050180}, {0x0, 0x203000}, {0x0, {0x0, 0x0}, {0x0, 0x0}, {0x25bf377, ...}, ...})
	github.com/sigstore/cosign/cmd/cosign/cli/sign/sign.go:425 +0x128
github.com/sigstore/cosign/cmd/cosign/cli/sign.SignCmd({_, _}, {0x0, {0x0, 0x0}, {0x0, 0x0}, {0x25bf377, 0x1e}, {0x25b3dda, ...}, ...}, ...)
	github.com/sigstore/cosign/cmd/cosign/cli/sign/sign.go:117 +0x245
github.com/sigstore/cosign/cmd/cosign/cli.Sign.func1(0xc000901680, {0xc0002cbe20, 0x1, 0x1})
	github.com/sigstore/cosign/cmd/cosign/cli/sign.go:92 +0x3d6
github.com/spf13/cobra.(*Command).execute(0xc000901680, {0xc0002cbd80, 0x1, 0x1})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ff900)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	github.com/sigstore/cosign/cmd/cosign/main.go:45 +0x4c
```

**Comment by mudler** [comment]
This https://github.com/rancher-sandbox/cOS-toolkit/pull/979 temporarly downgrades to 1.3.1 until we figure what's wrong with 1.4.x.

**Comment by mudler** [comment]
Also, seems 1.4.x clients can't validate anymore signatures for 1.3.x https://github.com/rancher-sandbox/cOS-toolkit/runs/4548389594?check_suite_focus=true

**Comment by mudler** [comment]
@Itxaka when master will be green I'll close this one and track the cosign bump separately (so we can also revert my downgrade)

**Comment by Itxaka** [comment]
Problem is, how do we test this properly? without incurring in pushing artifacts for the sake of it or --forcing the existing artifacts to be pushed?

**Comment by Itxaka** [comment]
Aslo master is green: https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/1591154096

**Comment by mudler** [comment]
> Problem is, how do we test this properly? without incurring in pushing artifacts for the sake of it or --forcing the existing artifacts to be pushed?

To avoid this happening in the future, we should imho have a staging repository. It should change a bit our pipelines, but will help catch this kinda of issues before-ahead.

The CI currently builds off changes and creates an intermediate repository where tests are run against. Instead of doing this, the CI should just push everything into a staging repository, perform tests from there, and then push to master only if tests are passing. In this way we can target tests against staging and later on just move artifacts.

**Comment by mudler** [comment]
> Aslo master is green: https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/1591154096

build side it is, but on client when cosign is enabled they see this for certain packages, that were signed with 1.4.x: https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/1592289194

**Comment by mudler** [comment]
All seems good now, examples are back to building

**Comment by Itxaka** [comment]
@mudler it shouldnt be closed. AFAIK the new signatures will not be validated by pointing to the old fulcio url, so we would need to resign the latest packages with the old url as well, otherwise the validation for those packages will never succeed.

**Comment by mudler** [comment]
> @mudler it shouldnt be closed. AFAIK the new signatures will not be validated by pointing to the old fulcio url, so we would need to resign the latest packages with the old url as well, otherwise the validation for those packages will never succeed.

maybe open a follow-up? this card is about master failing pushing, which now succeeds.

Besides, new packages have been built with 1.3.x, so the error is gone from the client too (see examples builds)

**Comment by Itxaka** [comment]
wow, then I dont understand anything. I would think that signatures with 1.4 would not be compatible with the older fulcio endpoint...I guess Im wrong.
