### ISSUE TITLE
Boot failure on RPi3

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#980]
Building an SD-card image for Raspberry Pi 3/4 using the steps under "to reproduce" below fails to produce a bootable RPi3 image.
Booting RPi 4 is fine.

**Describe the bug**

I see this in the journal:

```
Nov 09 12:00:10 localhost kernel: gpiochip_add_data_with_key: GPIOs 450..503 (pinctrl-bcm2835) failed to register, -517
Nov 09 12:00:10 localhost kernel: pinctrl-bcm2835 3f200000.gpio: could not add GPIO chip
Nov 09 12:03:24 localhost dracut-initqueue[508]: Warning: dracut-initqueue timeout - starting timeout scripts
Nov 09 12:03:25 localhost dracut-initqueue[508]: Warning: dracut-initqueue timeout - starting timeout scripts
```
Note the 3:14 minutes delay before the dracut output starts.

and then
```
Nov 09 12:05:01 localhost systemd[1]: dev-disk-by\x2dlabel-COS_ACTIVE.device: Job dev-disk-by\x2dlabel-COS_ACTIVE.device/start timed out.
Nov 09 12:05:01 localhost systemd[1]: Timed out waiting for device /dev/disk/by-label/COS_ACTIVE.
Nov 09 12:05:01 localhost systemd[1]: Dependency failed for Initrd Root Device.
```

**To Reproduce**

Git checkouts of latest `cos-toolkit` and `luet`

```
export rev=rpi64
sudo make create-repo
sudo -E make PACKAGES="firmware/u-boot-${rev}" build
sudo -E make PACKAGES="firmware/raspberrypi-firmware" build
sudo -E make PACKAGES="firmware/raspberrypi-firmware-config" build
sudo -E make PACKAGES="firmware/raspberrypi-firmware-dt" build
sudo make create-repo
sudo ./images/arm-img-builder.sh --model ${rev} --local
```

`dd` the resulting `arm.img` to an sd-card.

**Expected behavior**

Identical boot behaviour for RPi3 and RPi4

**Logs**

See next comment

**Additional context**

**Comment by kkaempf** [comment]
Full journal:
[journal.txt](https://github.com/rancher-sandbox/cOS-toolkit/files/7727796/journal.txt)

**Comment by mudler** [comment]
I've tested quay.io/costoolkit/examples:rpi-0.7.9-13-gbca5b092.img from the CI on RPI3 and boots fine here.

Maybe related to https://github.com/rancher-sandbox/cOS-toolkit/pull/967 ? @davidcassany  shall we offer customizable timeouts for active/passive too?

**Comment by kkaempf** [comment]
Hmm, my version was from yesterday. Did an update of luet and cos-toolkit to latest and now both RasPis boot.
Sorry for the noise 🤦🏻

**Comment by davidcassany** [comment]
> I've tested quay.io/costoolkit/examples:rpi-0.7.9-13-gbca5b092.img from the CI on RPI3 and boots fine here.
> 
> Maybe related to #967 ? @davidcassany shall we maybe offer customizable timeouts for active/passive too?

It shouldn't be hard, but rather than that I'd vote for extending the default timeout. Note that this device (`COS_ACTIVE`) is a hard requirement and in most functional cases this will take few seconds to be discovered by udev and systemd. Extending the timeout is only extending fail time for broken setups and possibly enabling slow devices to succeed.

Note current timeout is 300 seconds, which is already quite a lot. If in 300 seconds `COS_STATE` and `COS_ACTIVE` did not appear it is likely that the problem is not a too short timeout.

For reference the timeout is set here https://github.com/rancher-sandbox/cOS-toolkit/blob/5369128b87398f54edb0f4e7af45b1c64fb2c077/packages/immutable-rootfs/30cos-immutable-rootfs/cos-generator.sh#L124-L129

**Comment by mudler** [comment]
> > I've tested quay.io/costoolkit/examples:rpi-0.7.9-13-gbca5b092.img from the CI on RPI3 and boots fine here.
> > Maybe related to #967 ? @davidcassany shall we maybe offer customizable timeouts for active/passive too?
> 
> It shouldn't be hard, but rather than that I'd vote for extending the default timeout. Note that this device (`COS_ACTIVE`) is a hard requirement and in most functional cases this will take few seconds to be discovered by udev and systemd. Extending the timeout is only extending fail time for broken setups and possibly enabling slow devices to succeed.

Yep sounds good, I had in mind this just for particularly slow devices, e.g. if you have a rather outdated sd card which is a low class level.
