### ISSUE TITLE
`elemental run-stage`

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#987]
This is a follow-up of https://github.com/rancher-sandbox/cOS-toolkit/issues/942.

Port [cos-setup](https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/cos-setup/cos-setup) logic into a `run-stage` golang subcommand of elemental-cli and consume it in cos toolkit

**Comment by mudler** [comment]
@Itxaka do we consume already run-stage from elemental-cli in cOS?

**Comment by Itxaka** [comment]
Nope, this was auto closed due to the linked pr I think!

**Comment by Itxaka** [comment]
ah no, I did move it, so I mistaked this issue for a different one...ups...
