### ISSUE TITLE
`cos-upgrade` fails on RPi3

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/cOS-toolkit#989]
**cos-toolkit version:**

cos-toolkit @ 18db961c44b22a922a56aadda750983dfe1c433a
luet @ 0.21.0

**CPU architecture, OS, and Version:**

Raspberry Pi 3 Model B V 1.2 (1GB)

**Describe the bug**

```
cos:~ # cos-upgrade 
Upgrading system..
blkid: option requires an argument -- 'L'
Try 'blkid --help' for more information.
State partition cannot be found
```

**To Reproduce**

see above

**Expected behavior**

A better error message, maybe :wink:

**Logs**

**Additional context**

**Comment by mudler** [comment]
See #930, a COS_PERSISTENT partition is required in order to perform upgrades, but is not part of the default SD image

**Comment by mudler** [comment]
This is the new message now, which is tied to the fact that `COS_PERSISTENT` is not set:

```
cos:~ # cos-upgrade
Upgrading system..
Persistent partition cannot be found
cos:~ # 
```

**Comment by mudler** [comment]
See https://github.com/rancher-sandbox/cOS-toolkit/issues/930#issuecomment-999630097 for an example on how to setup a 'fake' `COS_PERSISTENT` via cloud-init (mainly for testing)
